<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraContentTestimonialsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_content_testimonials')->delete();

        \DB::table('lara_content_testimonials')->insert([
            0 => [
                'id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Darrell Steward',
                'slug' => 'darrell-steward',
                'slug_lock' => 0,
                'lead' => '<p>Dolor, a eget elementum, integer nulla volutpat, nunc, sit. Quam iaculis varius mauris magna sem. Egestas sed sed suscipit dolor faucibus dui imperdiet at eget. Tincidunt imperdiet quis hendrerit aliquam feugiat neque cras sed. Dictum quam integer volutpat tellus, faucibus platea. Pulvinar turpis proin faucibus at mauris. Sagittis gravida vitae porta enim, nulla arcu fermentum massa volutpat pretium.</p>',
                'body' => null,
                'quoteshort' => 'Cool and experienced team to develop your web application',
                'role' => 'Co-founder of Lorem Company',
                'stars' => '5',
                'created_at' => '2025-08-24 12:36:50',
                'updated_at' => '2025-12-24 12:19:03',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:36:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            1 => [
                'id' => 2,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Annette Black',
                'slug' => 'annette-black',
                'slug_lock' => 0,
                'lead' => '<p>Vero minima sequi adipisci architecto dolorum, error animi delectus dicta perferendis! A, exercitationem soluta quam reprehenderit rem animi amet eligendi voluptates consequatur ipsam pariatur necessitatibus laboriosam in illo eos molestias ex explicabo eaque assumenda voluptatibus ducimus consectetur perferendis! Architecto molestias, rerum reprehenderit amet sunt natus fuga blanditiis suscipit.</p>',
                'body' => null,
                'quoteshort' => 'Efficient and Innovative: Our Experience with Silicon.',
                'role' => 'Strategic Advisor at Company LLC',
                'stars' => '4',
                'created_at' => '2025-08-24 12:44:37',
                'updated_at' => '2025-12-24 12:19:31',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:44:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            2 => [
                'id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'John MacIntosh',
                'slug' => 'john-macintosh',
                'slug_lock' => 0,
                'lead' => '<p>In quas adipisci assumenda voluptas eveniet obcaecati est quis sapiente voluptatum iste porro blanditiis debitis ut beatae, fugit quidem fugiat eum molestias? Dolore magni harum officia tempore eos sapiente. Voluptatibus pariatur omnis libero unde quasi optio, tenetur reprehenderit tempore necessitatibus harum mollitia qui. Maxime, quas tempore. Sunt quaerat porro facere blanditiis voluptatibus.</p>',
                'body' => null,
                'quoteshort' => 'Exceptional Service and Quality Results.',
                'role' => 'Founder & CEO, Uber',
                'stars' => '5',
                'created_at' => '2025-08-24 12:46:29',
                'updated_at' => '2025-12-24 12:21:43',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:46:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            3 => [
                'id' => 4,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Annette Black',
                'slug' => 'annette-black-2',
                'slug_lock' => 0,
                'lead' => '<p>Mi semper risus ultricies orci pulvinar in at enim orci. Quis facilisis nunc pellentesque in ullamcorper sit. Lorem blandit arcu sapien, senectus libero, amet dapibus cursus quam. Eget pellentesque eu purus volutpat adipiscing malesuada. Purus nisi, tortor vel lacus.</p>',
                'body' => null,
                'quoteshort' => null,
                'role' => 'Strategic Advisor at Company LLC',
                'stars' => '5',
                'created_at' => '2025-08-24 12:48:52',
                'updated_at' => '2025-12-24 12:22:15',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:48:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            4 => [
                'id' => 5,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Ralph Edwards',
                'slug' => 'ralph-edwards',
                'slug_lock' => 0,
                'lead' => '<p>Vestibulum nunc lectus auctor quis. Natoque lectus tortor lacus, eu. Nunc feugiat nisl maecenas nulla hac morbi. Vitae, donec facilisis sed nunc netus. Venenatis posuere faucibus enim est. Vel dignissim morbi blandit morbi tellus. Arcu ullamcorper quis enim.</p>',
                'body' => null,
                'quoteshort' => null,
                'role' => 'Head of Marketing at Lorem Ltd.',
                'stars' => '5',
                'created_at' => '2025-08-24 12:51:01',
                'updated_at' => '2025-12-24 12:22:42',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:50:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            5 => [
                'id' => 6,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Darrell Steward',
                'slug' => 'darrell-steward-2',
                'slug_lock' => 0,
                'lead' => '<p>Ac at sed sit senectus massa. Massa ante amet ultrices magna porta tempor. Aliquet diam in et magna ultricies mi at. Lectus enim, vel enim egestas nam pellentesque et leo. Elit mi faucibus laoreet aliquam pellentesque sed aliquet integer massa. Orci leo tortor ornare.</p>',
                'body' => null,
                'quoteshort' => null,
                'role' => 'Project Manager at Ipsum Ltd.',
                'stars' => null,
                'created_at' => '2025-08-24 12:52:56',
                'updated_at' => '2025-12-24 12:22:58',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-24 12:52:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            6 => [
                'id' => 7,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Voluptatem id occaecati vel maiores.',
                'slug' => 'voluptatem-id-occaecati-vel-maiores',
                'slug_lock' => 0,
                'lead' => 'Velit recusandae expedita esse sed qui dignissimos. Esse aliquam pariatur provident veritatis recusandae.',
                'body' => null,
                'quoteshort' => 'Sed pariatur itaque.',
                'role' => 'Est quia excepturi.',
                'stars' => null,
                'created_at' => '2026-09-26 12:01:22',
                'updated_at' => '2026-09-26 12:01:22',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2026-09-26 12:01:22',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
        ]);

    }
}
