<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraMenuMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_menu_menu_items')->delete();
        
        \DB::table('lara_menu_menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Home',
                'slug' => 'home',
                'slug_lock' => 0,
                'type' => 'page',
                'is_home' => 1,
                'route' => NULL,
                'routename' => 'entity.pages.1.show.5',
                'route_has_auth' => 0,
                'entity_id' => 1,
                'entity_view_id' => 101,
                'object_id' => 5,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 1,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'position' => 1001,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'About',
                'slug' => 'about',
                'slug_lock' => 0,
                'type' => 'page',
                'is_home' => 0,
                'route' => 'about',
                'routename' => 'entity.pages.2.show.2',
                'route_has_auth' => 0,
                'entity_id' => 1,
                'entity_view_id' => 101,
                'object_id' => 2,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'position' => 1002,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            2 => 
            array (
                'id' => 7,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 2,
                'title' => 'Contact',
                'slug' => 'contact-2',
                'slug_lock' => 0,
                'type' => 'form',
                'is_home' => 0,
                'route' => 'contact-2',
                'routename' => 'form.contactforms.7.form',
                'route_has_auth' => 0,
                'entity_id' => 43,
                'entity_view_id' => 105,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 33,
                'rgt' => 34,
                'depth' => 0,
                'position' => 2001,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            3 => 
            array (
                'id' => 13,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Firmaq',
                'slug' => 'firmaq',
                'slug_lock' => 0,
                'type' => 'url',
                'is_home' => 0,
                'route' => NULL,
                'routename' => NULL,
                'route_has_auth' => 0,
                'entity_id' => NULL,
                'entity_view_id' => NULL,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => 'https://www.firmaq.nl/nl',
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 0,
                'parent_id' => NULL,
                'lft' => 23,
                'rgt' => 24,
                'depth' => 0,
                'position' => 1012,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            4 => 
            array (
                'id' => 16,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Blog',
                'slug' => 'blog',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'blog',
                'routename' => 'entitytag.blogs.16.index',
                'route_has_auth' => 0,
                'entity_id' => 2,
                'entity_view_id' => 201,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'position' => 1005,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            5 => 
            array (
                'id' => 20,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Team',
                'slug' => 'team',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'team',
                'routename' => 'entitytag.teams.20.index',
                'route_has_auth' => 0,
                'entity_id' => 3,
                'entity_view_id' => 103,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'position' => 1003,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            6 => 
            array (
                'id' => 21,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Services',
                'slug' => 'services',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'services',
                'routename' => 'entitytag.services.21.index',
                'route_has_auth' => 0,
                'entity_id' => 61,
                'entity_view_id' => 203,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'position' => 1004,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            7 => 
            array (
                'id' => 22,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Laravel Events',
                'slug' => 'laravel-events',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'laravel-events',
                'routename' => 'entitytag.events.22.laravel.index',
                'route_has_auth' => 0,
                'entity_id' => 44,
                'entity_view_id' => 106,
                'object_id' => NULL,
                'tag_id' => 2083,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 0,
                'position' => 1007,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            8 => 
            array (
                'id' => 23,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Media',
                'slug' => 'media',
                'slug_lock' => 0,
                'type' => 'parent',
                'is_home' => 0,
                'route' => 'media',
                'routename' => NULL,
                'route_has_auth' => 0,
                'entity_id' => NULL,
                'entity_view_id' => NULL,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 15,
                'rgt' => 22,
                'depth' => 0,
                'position' => 1008,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            9 => 
            array (
                'id' => 24,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Gallery',
                'slug' => 'photo-album',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'media/photo-album',
                'routename' => 'entitytag.galleries.24.index',
                'route_has_auth' => 0,
                'entity_id' => 64,
                'entity_view_id' => 207,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => 23,
                'lft' => 16,
                'rgt' => 17,
                'depth' => 1,
                'position' => 1009,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            10 => 
            array (
                'id' => 25,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Videos',
                'slug' => 'videos',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'media/videos',
                'routename' => 'entity.videos.25.index',
                'route_has_auth' => 0,
                'entity_id' => 66,
                'entity_view_id' => 211,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => 23,
                'lft' => 18,
                'rgt' => 19,
                'depth' => 1,
                'position' => 1010,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            11 => 
            array (
                'id' => 26,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Downloads',
                'slug' => 'downloads',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'media/downloads',
                'routename' => 'entitytag.docs.26.index',
                'route_has_auth' => 1,
                'entity_id' => 65,
                'entity_view_id' => 209,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => 23,
                'lft' => 20,
                'rgt' => 21,
                'depth' => 1,
                'position' => 1011,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            12 => 
            array (
                'id' => 27,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Privacy',
                'slug' => 'privacy',
                'slug_lock' => 0,
                'type' => 'page',
                'is_home' => 0,
                'route' => 'privacy',
                'routename' => 'entity.pages.27.show.25',
                'route_has_auth' => 0,
                'entity_id' => 1,
                'entity_view_id' => 101,
                'object_id' => 25,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 1,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 0,
                'parent_id' => NULL,
                'lft' => 31,
                'rgt' => 32,
                'depth' => 0,
                'position' => 1016,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            13 => 
            array (
                'id' => 28,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Contact',
                'slug' => 'contact',
                'slug_lock' => 0,
                'type' => 'form',
                'is_home' => 0,
                'route' => 'contact',
                'routename' => 'form.contactforms.28.form',
                'route_has_auth' => 0,
                'entity_id' => 43,
                'entity_view_id' => 105,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 25,
                'rgt' => 26,
                'depth' => 0,
                'position' => 1013,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            14 => 
            array (
                'id' => 29,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Classicform',
                'slug' => 'classicform',
                'slug_lock' => 0,
                'type' => 'form',
                'is_home' => 0,
                'route' => 'classicform',
                'routename' => 'form.classicforms.29.form',
                'route_has_auth' => 0,
                'entity_id' => 69,
                'entity_view_id' => 213,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 0,
                'parent_id' => NULL,
                'lft' => 27,
                'rgt' => 30,
                'depth' => 0,
                'position' => 1014,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            15 => 
            array (
                'id' => 30,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Thank you',
                'slug' => 'thank-you',
                'slug_lock' => 0,
                'type' => 'page',
                'is_home' => 0,
                'route' => 'classicform/thank-you',
                'routename' => 'entity.pages.30.show.26',
                'route_has_auth' => 0,
                'entity_id' => 1,
                'entity_view_id' => 101,
                'object_id' => 26,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 0,
                'parent_id' => 29,
                'lft' => 28,
                'rgt' => 29,
                'depth' => 1,
                'position' => 1015,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            16 => 
            array (
                'id' => 31,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 1,
                'title' => 'Events',
                'slug' => 'events',
                'slug_lock' => 0,
                'type' => 'entity',
                'is_home' => 0,
                'route' => 'events',
                'routename' => 'entitytag.events.31.index',
                'route_has_auth' => 0,
                'entity_id' => 44,
                'entity_view_id' => 106,
                'object_id' => NULL,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 1,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 0,
                'parent_id' => NULL,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 0,
                'position' => 1006,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            17 => 
            array (
                'id' => 32,
                'language' => 'nl',
                'language_parent' => NULL,
                'menu_id' => 2,
                'title' => 'Privacy',
                'slug' => 'privacy-2',
                'slug_lock' => 0,
                'type' => 'page',
                'is_home' => 0,
                'route' => 'privacy-2',
                'routename' => 'entity.pages.32.show.25',
                'route_has_auth' => 0,
                'entity_id' => 1,
                'entity_view_id' => 101,
                'object_id' => 25,
                'tag_id' => NULL,
                'url' => NULL,
                'locked_by_admin' => 0,
                'updated_at' => NULL,
                'created_at' => NULL,
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 35,
                'rgt' => 36,
                'depth' => 0,
                'position' => 2002,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
        ));
        
        
    }
}