<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraResourceEntityViewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_resource_entity_views')->delete();

        \DB::table('lara_resource_entity_views')->insert(array (
            0 =>
            array (
                'id' => 101,
                'entity_id' => 1,
                'title' => 'Page Standard',
                'method' => 'show',
                'filename' => 'show',
                'template' => 'standard',
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            1 =>
            array (
                'id' => 102,
                'entity_id' => 1,
                'title' => 'Page Landing',
                'method' => 'show',
                'filename' => 'show',
                'template' => 'landing',
                'template_extra_fields' => 2,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            2 =>
            array (
                'id' => 103,
                'entity_id' => 3,
                'title' => 'Team Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid4',
                'image_required' => 1,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            3 =>
            array (
                'id' => 104,
                'entity_id' => 3,
                'title' => 'Team Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            4 =>
            array (
                'id' => 105,
                'entity_id' => 43,
                'title' => 'contactform',
                'method' => 'form',
                'filename' => 'form',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => NULL,
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            5 =>
            array (
                'id' => 106,
                'entity_id' => 44,
                'title' => 'Event Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            6 =>
            array (
                'id' => 107,
                'entity_id' => 44,
                'title' => 'Event Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            7 =>
            array (
                'id' => 201,
                'entity_id' => 2,
                'title' => 'Blog Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => 6,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            8 =>
            array (
                'id' => 202,
                'entity_id' => 2,
                'title' => 'Blog Single',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
            ),
            9 =>
            array (
                'id' => 203,
                'entity_id' => 61,
                'title' => 'Service Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => 'filterbytaxonomy',
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            10 =>
            array (
                'id' => 204,
                'entity_id' => 61,
                'title' => 'Service Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            11 =>
            array (
                'id' => 205,
                'entity_id' => 62,
                'title' => 'Testimonial Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => NULL,
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            12 =>
            array (
                'id' => 206,
                'entity_id' => 62,
                'title' => 'Testimonial Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            13 =>
            array (
                'id' => 207,
                'entity_id' => 64,
                'title' => 'Gallery Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            14 =>
            array (
                'id' => 208,
                'entity_id' => 64,
                'title' => 'Gallery Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            15 =>
            array (
                'id' => 209,
                'entity_id' => 65,
                'title' => 'Doc index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => '_sortbytaxonomy',
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            16 =>
            array (
                'id' => 210,
                'entity_id' => 65,
                'title' => 'Doc Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            17 =>
            array (
                'id' => 211,
                'entity_id' => 66,
                'title' => 'Video Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            18 =>
            array (
                'id' => 212,
                'entity_id' => 66,
                'title' => 'Video Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            19 =>
            array (
                'id' => 213,
                'entity_id' => 69,
                'title' => 'classicform',
                'method' => 'form',
                'filename' => 'form',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => NULL,
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            20 =>
            array (
                'id' => 214,
                'entity_id' => 70,
                'title' => 'Product Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            21 =>
            array (
                'id' => 215,
                'entity_id' => 70,
                'title' => 'Product Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
            ),
            22 =>
            array (
                'id' => 216,
                'entity_id' => 73,
                'title' => 'City Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 1,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ),
            23 =>
            array (
                'id' => 217,
                'entity_id' => 73,
                'title' => 'City Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => NULL,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => NULL,
                'paginate' => NULL,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
            ),
        ));


    }
}