<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraBlocksSlidersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_blocks_sliders')->delete();
        
        \DB::table('lara_blocks_sliders')->insert(array (
            0 => 
            array (
                'id' => 2,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'The Best Solutions for Your Business',
                'slug' => 'the-best-solutions-for-your-business',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Start your project',
                'urltitle' => 'Start your project',
                'url' => '#',
                'payoff' => '<p>We provide the wide range of high quality services and best practices solutions<br>to our customers making their business better.</p>',
                'subtitle' => NULL,
                'captiontype' => NULL,
                'type' => 'payoff',
                'created_at' => '2025-07-06 16:11:23',
                'updated_at' => '2025-08-25 07:52:14',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-06 16:11:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Award-Winning Software Company',
                'slug' => 'award-winning-software-company',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Get in touch',
                'urltitle' => 'Get in touch',
                'url' => '#',
                'payoff' => '<p> We are a dedicated team of passionate product managers, full stack developers, UX/UI designers</p>',
                'subtitle' => NULL,
                'captiontype' => NULL,
                'type' => 'payoff',
                'created_at' => '2025-07-06 17:47:57',
                'updated_at' => '2025-08-25 07:52:42',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-06 17:47:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'This Technology May Change the World',
                'slug' => 'this-technology-may-change-the-world',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Join our team',
                'urltitle' => 'Join our team',
                'url' => '#',
                'payoff' => '<p>This Content Management System is fast, stable, and has an incredible user experience</p>',
                'subtitle' => NULL,
                'captiontype' => NULL,
                'type' => 'payoff',
                'created_at' => '2025-07-06 17:54:25',
                'updated_at' => '2025-08-25 07:53:08',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-06 17:54:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Cashless payment case study',
                'slug' => 'cashless-payment-case-study',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '10',
                'overlaycolor' => 'black',
                'urltext' => 'View case study',
                'urltitle' => 'Cashless payment case study',
                'url' => '#',
                'payoff' => '<p></p>',
                'subtitle' => 'Payment Service Provider Company',
                'captiontype' => NULL,
                'type' => 'payoff',
                'created_at' => '2025-08-25 10:31:16',
                'updated_at' => '2025-08-25 10:32:56',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 10:30:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Smart tech case study',
                'slug' => 'smart-tech-case-study',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '0',
                'overlaycolor' => 'black',
                'urltext' => NULL,
                'urltitle' => NULL,
                'url' => NULL,
                'payoff' => '<p>Adipiscing quis a at ligula. Gravida gravida diam rhoncus cursus in. Turpis sagittis tempor gravida phasellus sapien. Faucibus donec consectetur sed id sit nisl.</p>',
                'subtitle' => 'Data Analytics Company',
                'captiontype' => NULL,
                'type' => 'payoff',
                'created_at' => '2025-08-25 10:35:39',
                'updated_at' => '2025-08-25 10:37:00',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 10:35:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
            ),
        ));
        
        
    }
}