<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraResourceEntityViewsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_resource_entity_views')->delete();

        \DB::table('lara_resource_entity_views')->insert([
            0 => [
                'id' => 101,
                'entity_id' => 1,
                'title' => 'Page Standard',
                'method' => 'show',
                'filename' => 'show',
                'template' => 'standard',
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            1 => [
                'id' => 102,
                'entity_id' => 1,
                'title' => 'Page Landing',
                'method' => 'show',
                'filename' => 'show',
                'template' => 'landing',
                'template_extra_fields' => 2,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            2 => [
                'id' => 103,
                'entity_id' => 3,
                'title' => 'Team Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid4',
                'image_required' => 1,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            3 => [
                'id' => 104,
                'entity_id' => 3,
                'title' => 'Team Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            4 => [
                'id' => 105,
                'entity_id' => 43,
                'title' => 'contactform',
                'method' => 'form',
                'filename' => 'form',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => null,
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            5 => [
                'id' => 106,
                'entity_id' => 44,
                'title' => 'Event Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            6 => [
                'id' => 107,
                'entity_id' => 44,
                'title' => 'Event Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            7 => [
                'id' => 201,
                'entity_id' => 2,
                'title' => 'Blog Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 1,
                'showtags' => null,
                'paginate' => 6,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            8 => [
                'id' => 202,
                'entity_id' => 2,
                'title' => 'Blog Single',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
            ],
            9 => [
                'id' => 203,
                'entity_id' => 61,
                'title' => 'Service Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => 'filterbytaxonomy',
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            10 => [
                'id' => 204,
                'entity_id' => 61,
                'title' => 'Service Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            11 => [
                'id' => 205,
                'entity_id' => 62,
                'title' => 'Testimonial Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => null,
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            12 => [
                'id' => 206,
                'entity_id' => 62,
                'title' => 'Testimonial Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            13 => [
                'id' => 207,
                'entity_id' => 64,
                'title' => 'Gallery Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            14 => [
                'id' => 208,
                'entity_id' => 64,
                'title' => 'Gallery Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            15 => [
                'id' => 209,
                'entity_id' => 65,
                'title' => 'Doc index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'list',
                'image_required' => 0,
                'showtags' => '_sortbytaxonomy',
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            16 => [
                'id' => 210,
                'entity_id' => 65,
                'title' => 'Doc Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            17 => [
                'id' => 211,
                'entity_id' => 66,
                'title' => 'Video Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            18 => [
                'id' => 212,
                'entity_id' => 66,
                'title' => 'Video Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            19 => [
                'id' => 213,
                'entity_id' => 69,
                'title' => 'classicform',
                'method' => 'form',
                'filename' => 'form',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => null,
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            20 => [
                'id' => 214,
                'entity_id' => 70,
                'title' => 'Product Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => 'grid3',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            21 => [
                'id' => 215,
                'entity_id' => 70,
                'title' => 'Product Show',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => '_single',
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
            ],
            22 => [
                'id' => 218,
                'entity_id' => 63,
                'title' => 'Portfolio Index',
                'method' => 'index',
                'filename' => 'index',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 0,
                'list_type' => null,
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
            23 => [
                'id' => 219,
                'entity_id' => 63,
                'title' => 'Portfolio Single',
                'method' => 'show',
                'filename' => 'show',
                'template' => null,
                'template_extra_fields' => 0,
                'is_single' => 1,
                'list_type' => null,
                'image_required' => 0,
                'showtags' => null,
                'paginate' => null,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
            ],
        ]);

    }
}
