<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraContentTeamsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_content_teams')->delete();

        \DB::table('lara_content_teams')->insert([
            0 => [
                'id' => 1,
                'location_id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Wilson',
                'slug' => 'jenny-wilson',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => 'JennyWilson15387',
                'twitter' => 'JennyWilson15387',
                'facebook' => 'JennyWilson15387',
                'email' => 'jenny.wilson@laracorp.com',
                'role' => 'Co-Founder & CEO',
                'middle_name' => null,
                'first_name' => 'Jenny',
                'created_at' => '2025-07-04 08:06:35',
                'updated_at' => '2026-08-09 09:57:43',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-04 17:39:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            1 => [
                'id' => 2,
                'location_id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Edwards',
                'slug' => 'ralph-edwards',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Co-Founder',
                'middle_name' => null,
                'first_name' => 'Ralph',
                'created_at' => '2025-07-04 15:38:39',
                'updated_at' => '2025-12-24 12:13:20',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-04 15:38:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            2 => [
                'id' => 3,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Williamson',
                'slug' => 'williamson',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Creative Director',
                'middle_name' => null,
                'first_name' => 'Cameron',
                'created_at' => '2025-07-09 13:33:20',
                'updated_at' => '2025-12-24 12:13:31',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:32:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            3 => [
                'id' => 4,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Bell',
                'slug' => 'bell',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Marketing Director',
                'middle_name' => null,
                'first_name' => 'Jerome',
                'created_at' => '2025-07-09 13:35:21',
                'updated_at' => '2025-12-24 12:13:42',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:34:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            4 => [
                'id' => 5,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'McKinney',
                'slug' => 'mckinney',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Lead Designer',
                'middle_name' => null,
                'first_name' => 'Marvin',
                'created_at' => '2025-07-09 13:36:13',
                'updated_at' => '2025-12-24 12:13:54',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:35:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            5 => [
                'id' => 6,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Howard',
                'slug' => 'howard',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Motion Designer',
                'middle_name' => null,
                'first_name' => 'Esther',
                'created_at' => '2025-07-09 13:38:45',
                'updated_at' => '2025-12-24 12:14:15',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:38:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            6 => [
                'id' => 7,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Steward',
                'slug' => 'steward',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Lead Developer',
                'middle_name' => null,
                'first_name' => 'Darrell',
                'created_at' => '2025-07-09 13:39:36',
                'updated_at' => '2025-12-24 12:14:27',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:39:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            7 => [
                'id' => 8,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Cooper',
                'slug' => 'cooper',
                'slug_lock' => 0,
                'lead' => null,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => null,
                'role' => 'Senior Project Manager',
                'middle_name' => null,
                'first_name' => 'Jane',
                'created_at' => '2025-07-09 13:40:37',
                'updated_at' => '2025-12-24 12:14:35',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:40:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
        ]);

    }
}
