<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraObjectLayoutTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_object_layout')->delete();

        \DB::table('lara_object_layout')->insert([
            0 => [
                'id' => 1,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 2,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_10',
                'share' => null,
                'cta' => 'contact',
                'footer' => null,
            ],
            1 => [
                'id' => 2,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 17,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            2 => [
                'id' => 3,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 19,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            3 => [
                'id' => 4,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 5,
                'header' => null,
                'hero' => 'hero_slider',
                'pagetitle' => null,
                'content' => 'full_width',
                'share' => null,
                'cta' => 'hidden',
                'footer' => null,
            ],
            4 => [
                'id' => 5,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 25,
                'header' => 'header_classic',
                'hero' => null,
                'pagetitle' => 'page_title_parallax',
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            5 => [
                'id' => 6,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 14,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_10',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            6 => [
                'id' => 7,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 34,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_10',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            7 => [
                'id' => 8,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 35,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            8 => [
                'id' => 9,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 36,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            9 => [
                'id' => 10,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 37,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_10',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            10 => [
                'id' => 11,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 38,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => 'hidden',
                'footer' => null,
            ],
            11 => [
                'id' => 12,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 40,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_10',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            12 => [
                'id' => 13,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 41,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_6',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            13 => [
                'id' => 14,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 42,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            14 => [
                'id' => 15,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 26,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => null,
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
            15 => [
                'id' => 16,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 50,
                'header' => null,
                'hero' => null,
                'pagetitle' => null,
                'content' => 'boxed_default_col_6',
                'share' => null,
                'cta' => null,
                'footer' => null,
            ],
        ]);

    }
}
