<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraFormClassicformsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_form_classicforms')->delete();

        \DB::table('lara_form_classicforms')->insert([
            0 => [
                'id' => 6,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2025-12-31 16:12:00',
                'updated_at' => '2025-12-31 16:12:00',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            1 => [
                'id' => 7,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2025-12-31 16:48:05',
                'updated_at' => '2025-12-31 16:48:05',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            2 => [
                'id' => 8,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-01-06 11:47:37',
                'updated_at' => '2026-01-06 11:47:37',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            3 => [
                'id' => 9,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 12:57:20',
                'updated_at' => '2026-04-24 12:57:20',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            4 => [
                'id' => 10,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:05:38',
                'updated_at' => '2026-04-24 13:05:38',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            5 => [
                'id' => 11,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:07:02',
                'updated_at' => '2026-04-24 13:07:02',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            6 => [
                'id' => 12,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:10:54',
                'updated_at' => '2026-04-24 13:10:54',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            7 => [
                'id' => 13,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:28:15',
                'updated_at' => '2026-04-24 13:28:15',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            8 => [
                'id' => 14,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:30:24',
                'updated_at' => '2026-04-24 13:30:24',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            9 => [
                'id' => 15,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:41:24',
                'updated_at' => '2026-04-24 13:41:24',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            10 => [
                'id' => 16,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:42:48',
                'updated_at' => '2026-04-24 13:42:48',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            11 => [
                'id' => 17,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:44:26',
                'updated_at' => '2026-04-24 13:44:26',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            12 => [
                'id' => 18,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:47:14',
                'updated_at' => '2026-04-24 13:47:14',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            13 => [
                'id' => 19,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:53:12',
                'updated_at' => '2026-04-24 13:53:12',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            14 => [
                'id' => 20,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:54:04',
                'updated_at' => '2026-04-24 13:54:04',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            15 => [
                'id' => 21,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:54:25',
                'updated_at' => '2026-04-24 13:54:25',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            16 => [
                'id' => 22,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:55:43',
                'updated_at' => '2026-04-24 13:55:43',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            17 => [
                'id' => 23,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:56:06',
                'updated_at' => '2026-04-24 13:56:06',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            18 => [
                'id' => 24,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:56:22',
                'updated_at' => '2026-04-24 13:56:22',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            19 => [
                'id' => 25,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 13:57:45',
                'updated_at' => '2026-04-24 13:57:45',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            20 => [
                'id' => 26,
                'email' => null,
                'name' => 'dsfgsdfg',
                'created_at' => '2026-04-24 13:59:41',
                'updated_at' => '2026-04-24 13:59:41',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            21 => [
                'id' => 27,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:07:50',
                'updated_at' => '2026-04-24 14:07:50',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            22 => [
                'id' => 28,
                'email' => null,
                'name' => 'sdfg',
                'created_at' => '2026-04-24 14:11:10',
                'updated_at' => '2026-04-24 14:11:10',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            23 => [
                'id' => 29,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:12:41',
                'updated_at' => '2026-04-24 14:12:41',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            24 => [
                'id' => 30,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:17:57',
                'updated_at' => '2026-04-24 14:17:57',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            25 => [
                'id' => 31,
                'email' => null,
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:18:45',
                'updated_at' => '2026-04-24 14:18:45',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            26 => [
                'id' => 32,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:23:12',
                'updated_at' => '2026-04-24 14:23:12',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            27 => [
                'id' => 33,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:25:11',
                'updated_at' => '2026-04-24 14:25:11',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            28 => [
                'id' => 34,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:25:35',
                'updated_at' => '2026-04-24 14:25:35',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            29 => [
                'id' => 35,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:28:40',
                'updated_at' => '2026-04-24 14:28:40',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            30 => [
                'id' => 36,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:31:00',
                'updated_at' => '2026-04-24 14:31:00',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            31 => [
                'id' => 37,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:31:26',
                'updated_at' => '2026-04-24 14:31:26',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            32 => [
                'id' => 38,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:32:10',
                'updated_at' => '2026-04-24 14:32:10',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            33 => [
                'id' => 39,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:34:03',
                'updated_at' => '2026-04-24 14:34:03',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            34 => [
                'id' => 40,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:34:22',
                'updated_at' => '2026-04-24 14:34:22',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            35 => [
                'id' => 41,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:34:26',
                'updated_at' => '2026-04-24 14:34:26',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            36 => [
                'id' => 42,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:34:33',
                'updated_at' => '2026-04-24 14:34:33',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            37 => [
                'id' => 43,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:34:44',
                'updated_at' => '2026-04-24 14:34:44',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            38 => [
                'id' => 44,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:36:15',
                'updated_at' => '2026-04-24 14:36:15',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            39 => [
                'id' => 45,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:38:47',
                'updated_at' => '2026-04-24 14:38:47',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            40 => [
                'id' => 46,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:39:30',
                'updated_at' => '2026-04-24 14:39:30',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            41 => [
                'id' => 47,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:40:23',
                'updated_at' => '2026-04-24 14:40:23',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            42 => [
                'id' => 48,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:40:50',
                'updated_at' => '2026-04-24 14:40:50',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            43 => [
                'id' => 49,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:41:05',
                'updated_at' => '2026-04-24 14:41:05',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            44 => [
                'id' => 50,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:41:19',
                'updated_at' => '2026-04-24 14:41:19',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
            45 => [
                'id' => 51,
                'email' => 's.hoeksma@firmaq.nl',
                'name' => 'Sybrand Hoeksma',
                'created_at' => '2026-04-24 14:41:53',
                'updated_at' => '2026-04-24 14:41:53',
                'deleted_at' => null,
                'ipaddress' => '127.0.0.1',
                'locked_at' => null,
                'locked_by' => null,
            ],
        ]);

    }
}
