<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraBlocksWidgetsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_blocks_widgets')->delete();
        
        \DB::table('lara_blocks_widgets')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'News from our Development Team',
                'slug' => 'latest-news',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur efficitur, tellus et lobortis congue, nisl ante semper odio, in suscipit turpis neque vitae elit. Curabitur ultricies velit vitae nulla lacinia, id pulvinar nulla facilisis. Vivamus non augue vitae risus luctus convallis non quis elit. Sed aliquam, augue quis mollis sagittis, odio sem faucibus magna, non lobortis nulla odio id diam.</p>',
                'template' => 'team_blogs',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => 'team-news',
                'resource_slug' => 'blogs',
                'max_items' => 3,
                'image_required' => 1,
                'type' => 'module',
                'is_global' => 0,
                'hook' => 'content_bottom',
                'created_at' => '2025-07-10 11:01:38',
                'updated_at' => '2026-03-15 16:20:41',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-10 13:10:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'We Have Social Networks',
                'slug' => 'we-have-social-networks',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'template' => 'about_social',
                'sortorder' => 30,
                'usecache' => 0,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 0,
                'hook' => 'content_bottom',
                'created_at' => '2025-07-10 13:07:36',
                'updated_at' => '2026-01-25 19:38:20',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-10 13:07:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Software Development',
                'slug' => 'software-development',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Commodo senectus massa est urna mi. Mattis dis arcu aenean libero viverra gravida.</p>',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 0,
                'hook' => 'home1',
                'created_at' => '2025-08-25 09:07:04',
                'updated_at' => '2026-03-10 09:45:33',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 09:06:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'App Development',
                'slug' => 'app-development',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Enim vehicula integer mattis morbi risus. Hendrerit pharetra arcu quam viverra.</p>',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 0,
                'hook' => 'home2',
                'created_at' => '2025-08-25 09:28:47',
                'updated_at' => '2025-12-24 12:32:19',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 09:26:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Support & Maintenance',
                'slug' => 'support-maintenance',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Turpis ultrices lacinia ut placerat dignissim morbi. Amet lectus sed tortor in elit adipiscing magnis.</p>',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 0,
                'hook' => 'home3',
                'created_at' => '2025-08-25 09:30:02',
                'updated_at' => '2025-12-24 12:32:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 09:29:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Software QA & Testing',
                'slug' => 'software-qa-testing',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Amet felis viverra proin feugiat. Eget metus metus lorem dolor pellentesque.</p>',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 0,
                'hook' => 'home4',
                'created_at' => '2025-08-25 09:32:01',
                'updated_at' => '2025-12-24 12:32:55',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 09:31:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Lara 10',
                'slug' => 'lara-10',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Proin ipsum pharetra, senectus eget scelerisque varius pretium platea velit. Lacus, eget eu vitae nullam proin turpis etiam mi sit. Non feugiat feugiat egestas nulla nec. Arcu tempus, eget elementum dolor ullamcorper sodales ultrices eros.</p>',
                'template' => 'footer',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 1,
                'hook' => 'footer1',
                'created_at' => '2025-08-25 11:22:36',
                'updated_at' => '2026-03-16 20:24:26',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 11:22:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Useful Links',
                'slug' => 'useful-links-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<ul><li><p><a href="#" rel="noopener noreferrer nofollow">Home</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">Services</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">Case Studies</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">About Us</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">News &amp; Insights</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">Terms &amp; Conditions</a></p></li><li><p><a href="#" rel="noopener noreferrer nofollow">Privacy Policy</a></p></li></ul><p></p>',
                'template' => 'footer_links',
                'sortorder' => 0,
                'usecache' => 0,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 1,
                'hook' => 'footer2',
                'created_at' => '2025-08-25 11:35:31',
                'updated_at' => '2026-03-10 08:32:56',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-25 11:35:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Socials',
                'slug' => 'socials',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'template' => 'footer_socials',
                'sortorder' => 0,
                'usecache' => 0,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 1,
                'hook' => 'footer3',
                'created_at' => '2025-09-04 13:55:48',
                'updated_at' => '2026-03-10 08:37:59',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-04 13:54:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Contact Us',
                'slug' => 'contact-us',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'template' => 'footer_contact',
                'sortorder' => 0,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => NULL,
                'max_items' => 0,
                'image_required' => 0,
                'type' => 'text',
                'is_global' => 1,
                'hook' => 'footer4',
                'created_at' => '2025-09-07 12:04:10',
                'updated_at' => '2025-09-07 12:04:24',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-07 12:03:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Our Team',
                'slug' => 'our-team',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'template' => 'default_teams',
                'sortorder' => 20,
                'usecache' => 1,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => NULL,
                'resource_slug' => 'teams',
                'max_items' => 8,
                'image_required' => 1,
                'type' => 'module',
                'is_global' => 0,
                'hook' => 'content_bottom',
                'created_at' => '2025-09-07 16:02:21',
                'updated_at' => '2026-03-14 16:56:07',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-07 16:01:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'What Our Clients Say About Us',
                'slug' => 'what-our-clients-say-about-us',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'template' => 'about_testimonials',
                'sortorder' => 10,
                'usecache' => 0,
                'linkurl' => NULL,
                'linktext' => NULL,
                'iconalign' => NULL,
                'iconclass' => NULL,
                'resource_term' => 'about',
                'resource_slug' => 'testimonials',
                'max_items' => 3,
                'image_required' => 0,
                'type' => 'module',
                'is_global' => 0,
                'hook' => 'content_bottom',
                'created_at' => '2025-09-07 16:51:11',
                'updated_at' => '2026-01-27 10:39:50',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-07 16:49:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'position' => NULL,
                'cgroup' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
        ));
        
        
    }
}