<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraContentBlogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_content_blogs')->delete();

        \DB::table('lara_content_blogs')->insert(array (
            0 =>
            array (
                'id' => 22,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'This Long-Awaited Technology May Finally Change the World',
                'slug' => 'this-long-awaited-technology-may-finally-change-the-world',
                'slug_lock' => 0,
                'lead' => '<p>Est quis sit phasellus proin proin fringilla eu quis. Placerat praesent blandit urna eu pellentesque dictum. Aliquam duis quam interdum quis.</p>',
                'body' => '<p>Purus ornare nisl est nec. Nunc, enim tellus pretium viverra quisque id in metus volutpat. Urna eget velit venenatis, commodo eget massa. Magna donec dictum cras nullam platea. Diam rhoncus massa lectus pellentesque tristique. Amet commodo, egestas vitae bibendum. Volutpat elit condimentum integer tortor porttitor justo vel lobortis risus. Lacinia pellentesque fermentum tellus orci mauris, velit duis eget. Commodo justo, hac ligula molestie felis, iaculis. Vitae dui at ante orci, dictum fusce. Urna, sed urna fringilla faucibus euismod aliquet nec. Quis libero, fermentum amet eu, condimentum auctor. Sit vel ipsum sem tempus gravida et. Scelerisque blandit orci, est quis. Nisi, tellus amet est nascetur habitant faucibus ornare et vivamus.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:21:18',
                'updated_at' => '2025-09-22 13:48:22',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-09 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => 'two',
                'position' => 0,
            ),
            1 =>
            array (
                'id' => 23,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'What the Software Stock Slump Means for the Market',
                'slug' => 'what-the-software-stock-slump-means-for-the-market',
                'slug_lock' => 0,
                'lead' => '<p>Id mollis consectetur congue egestas egestas suspendisse blandit justo. Tellus augue commodo id quis tempus etiam pulvinar at maecenas.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:27:44',
                'updated_at' => '2025-08-25 12:15:59',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-04 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            2 =>
            array (
                'id' => 24,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Mobile App Generates Data for the Energy Management',
                'slug' => 'mobile-app-generates-data-for-the-energy-management',
                'slug_lock' => 0,
                'lead' => '<p>Sociis sit risus id. Sit facilisis dolor arcu, fermentum vestibulum arcu ele. Pulvinar at maecenas maecenas pharetra, tincidunt sollicitudin in in.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:29:55',
                'updated_at' => '2025-08-25 12:15:33',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-05 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            3 =>
            array (
                'id' => 25,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'How the Millennial Lifestyle Changes as Service Prices Rise',
                'slug' => 'how-the-millennial-lifestyle-changes-as-service-prices-rise',
                'slug_lock' => 0,
                'lead' => '<p>Sit facilisis dolor arcu, fermentum vestibulum arcu elementum imperdiet. Mauris duis eleifend faucibus amet sagittis.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:33:11',
                'updated_at' => '2025-08-25 12:15:09',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-06 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            4 =>
            array (
                'id' => 26,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Why UX Design Matters and How it Affects Ranking',
                'slug' => 'why-ux-design-matters-and-how-it-affects-ranking',
                'slug_lock' => 0,
                'lead' => '<p>In mauris porttitor tincidunt mauris massa sit lorem sed scelerisque. Fringilla pharetra vel massa enim sollicitudin cras. At pulvinar eget sociis adipiscing eget donec ultricies nibh tristique. Adipiscing dui orci ac purus lacus.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:35:31',
                'updated_at' => '2025-08-25 12:14:20',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-07 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            5 =>
            array (
                'id' => 27,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'This Week in Search: New Limits and Exciting Features',
                'slug' => 'this-week-in-search-new-limits-and-exciting-features',
                'slug_lock' => 0,
                'lead' => '<p>Aliquet donec cras amet orci in in neque. Ut sed diam quis consectetur purus lorem eu, sit. Aliquam eget arcu sed urna feugiat. In integer nisl at dui malesuada. Diam pellentesque lobortis elementum lacus at in lectus.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:38:33',
                'updated_at' => '2025-08-25 12:13:47',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-08 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            6 =>
            array (
                'id' => 28,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'This Long-Awaited Technology May Finally Change the World',
                'slug' => 'this-long-awaited-technology-may-finally-change-the-world-2',
                'slug_lock' => 0,
                'lead' => 'Sapien, nulla placerat in at. Vitae tincidunt quam ornare massa porttitor. Neque a vitae feugiat in sit habitant integer. Cursus et at pulvinar sed neque vitae. Aliquam vitae hac phasellus purus lectus facilisi. Vitae vel ac quam.',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.<br><br>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:40:27',
                'updated_at' => '2025-06-24 08:41:36',
                'deleted_at' => '2025-06-24 08:41:36',
                'publish' => 1,
                'publish_from' => '2025-05-09 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            7 =>
            array (
                'id' => 29,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Inclusive Marketing: Why and How Does it Work?',
                'slug' => 'inclusive-marketing-why-and-how-does-it-work',
                'slug_lock' => 0,
                'lead' => '<p>Nunc aliquet scelerisque pellentesque imperdiet tortor elit, dictum. Tristique odio at dignissim viverra aliquet eleifend erat. Tellus, at arcu, egestas praesent. Varius aliquet pharetra adipiscing tincidunt orci nec neque.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 18:10:56',
                'updated_at' => '2025-08-25 12:12:33',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-10 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            8 =>
            array (
                'id' => 30,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'How Agile is Your Forecasting Process?',
                'slug' => 'how-agile-is-your-forecasting-process',
                'slug_lock' => 1,
                'lead' => '<p>Nulla fringilla arcu justo augue fringilla in nunc volutpat sit. Dui diam, faucibus vitae ultricies vitae mollis nunc elementum. Et, habitasse porta neque tempor tellus ut. Sagittis odio porttitor erat viverra erat neque.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum es. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 18:12:51',
                'updated_at' => '2025-10-17 08:54:48',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-11 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            9 =>
            array (
                'id' => 31,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Five Effective Landing Page Examples',
                'slug' => 'five-effective-landing-page-examples',
                'slug_lock' => 0,
                'lead' => '<p>Tellus sagittis dolor pellentesque vel porttitor magna aliquet arcu. Interdum risus mauris pulvinar et vel. Morbi tellus, scelerisque vel metus. Scelerisque arcu egestas ac commodo, ac nibh. Pretium ac elit sed nulla nec.</p>',
                'body' => '<p>Phasellus dapibus enim leo, sed lobortis est feugiat quis. Donec aliquet arcu mi, eget consectetur ex egestas vel. In vitae efficitur felis, sit amet egestas metus. Curabitur eget ipsum est. Nulla sem metus, rhoncus id ornare in, pellentesque vel felis. Aliquam placerat, odio et luctus lacinia, metus tellus scelerisque velit, quis tristique massa lacus et dolor. Aliquam sed elit vitae velit pharetra rutrum. Duis porta sapien purus, nec porta nisi dignissim at. Donec at urna et mauris porta venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p><p>Ut pretium, urna sit amet ultricies pulvinar, nisl lorem tincidunt lorem, non gravida neque odio sit amet urna. Aenean maximus egestas sapien quis mollis. Integer volutpat sem nec ex mollis, in posuere quam ultrices. Sed suscipit, quam at blandit laoreet, dui nisi ultricies nunc, suscipit malesuada felis tellus ut arcu. Donec non rhoncus lectus. Phasellus eu mauris leo. Quisque ac nisl feugiat, scelerisque augue id, condimentum nulla.</p><p>Suspendisse faucibus libero sit amet mi viverra, eu venenatis purus finibus. Mauris vehicula molestie purus ac vehicula. Ut pharetra posuere eros non malesuada. Curabitur tincidunt eu ex id volutpat. Etiam fringilla risus quis euismod luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et nisi leo. Proin dictum nulla vel massa faucibus, quis euismod augue dapibus. Donec dapibus metus vel leo fringilla, at egestas velit sagittis. Vestibulum varius purus magna, vel porttitor leo porta eu. Vestibulum bibendum eleifend ultrices. Sed euismod porta nunc, sed pellentesque massa molestie eget. Suspendisse nec justo et risus aliquet rutrum id sed arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 18:30:14',
                'updated_at' => '2025-10-17 08:26:51',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => '2025-05-12 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            10 =>
            array (
                'id' => 32,
                'user_id' => 1,
                'language' => 'en',
                'language_parent' => NULL,
                'title' => '[en] This Long-Awaited Technology May Finally Change the World',
                'slug' => 'this-long-awaited-technology-may-finally-change-the-world',
                'slug_lock' => 0,
                'lead' => '<p>Est quis sit phasellus proin proin fringilla eu quis. Placerat praesent blandit urna eu pellentesque dictum. Aliquam duis quam interdum quis.</p>',
                'body' => '<p>Purus ornare nisl est nec. Nunc, enim tellus pretium viverra quisque id in metus volutpat. Urna eget velit venenatis, commodo eget massa. Magna donec dictum cras nullam platea. Diam rhoncus massa lectus pellentesque tristique. Amet commodo, egestas vitae bibendum. Volutpat elit condimentum integer tortor porttitor justo vel lobortis risus. Lacinia pellentesque fermentum tellus orci mauris, velit duis eget. Commodo justo, hac ligula molestie felis, iaculis. Vitae dui at ante orci, dictum fusce. Urna, sed urna fringilla faucibus euismod aliquet nec. Quis libero, fermentum amet eu, condimentum auctor. Sit vel ipsum sem tempus gravida et. Scelerisque blandit orci, est quis. Nisi, tellus amet est nascetur habitant faucibus ornare et vivamus.</p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-06-01 15:21:18',
                'updated_at' => '2025-06-25 17:30:04',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-03 12:00:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
            11 =>
            array (
                'id' => 33,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'test',
                'slug' => 'test',
                'slug_lock' => NULL,
                'lead' => '<p></p>',
                'body' => '<p></p>',
                'body2' => NULL,
                'sticky' => 0,
                'source' => NULL,
                'created_at' => '2025-10-06 18:47:29',
                'updated_at' => '2025-10-06 18:47:37',
                'deleted_at' => '2025-10-06 18:47:37',
                'publish' => 0,
                'publish_from' => '2025-10-06 18:47:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'cgroup' => NULL,
                'position' => 0,
            ),
        ));


    }
}