<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraBlocksSlidersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lara_blocks_sliders')->delete();

        \DB::table('lara_blocks_sliders')->insert([
            0 => [
                'id' => 2,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'The Best Solutions for Your Business',
                'slug' => 'the-best-solutions-for-your-business',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Start your project',
                'urltitle' => 'Start your project',
                'url' => '#',
                'payoff' => '<p>We provide the wide range of high quality services and best practices solutions<br>to our customers making their business better.</p>',
                'subtitle' => null,
                'captiontype' => null,
                'type' => 'payoff',
                'created_at' => '2025-07-06 16:11:23',
                'updated_at' => '2026-03-20 18:55:37',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-06 16:11:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            1 => [
                'id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Award-Winning Software Company',
                'slug' => 'award-winning-software-company',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Get in touch',
                'urltitle' => 'Get in touch',
                'url' => '#',
                'payoff' => '<p> We are a dedicated team of passionate product managers, full stack developers, UX/UI designers</p>',
                'subtitle' => null,
                'captiontype' => null,
                'type' => 'payoff',
                'created_at' => '2025-07-06 17:47:57',
                'updated_at' => '2025-12-24 10:57:55',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-06 17:47:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            2 => [
                'id' => 4,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'This Technology May Change the World',
                'slug' => 'this-technology-may-change-the-world',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '40',
                'overlaycolor' => 'black',
                'urltext' => 'Join our team',
                'urltitle' => 'Join our team',
                'url' => '#',
                'payoff' => '<p>This Content Management System is fast, stable, and has an incredible user experience</p>',
                'subtitle' => null,
                'captiontype' => null,
                'type' => 'payoff',
                'created_at' => '2025-07-06 17:54:25',
                'updated_at' => '2025-12-24 10:58:14',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-07-06 17:54:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            3 => [
                'id' => 5,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Cashless payment case study',
                'slug' => 'cashless-payment-case-study',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '10',
                'overlaycolor' => 'black',
                'urltext' => 'View case study',
                'urltitle' => 'Cashless payment case study',
                'url' => '#',
                'payoff' => '<p>Aenean dolor elit tempus tellus imperdiet. Elementum, ac convallis morbi sit est feugiat ultrices. Cras tortor maecenas pulvinar nec ac justo. Massa sem eget semper...</p>',
                'subtitle' => 'Payment Service Provider Company',
                'captiontype' => null,
                'type' => 'payoff',
                'created_at' => '2025-08-25 10:31:16',
                'updated_at' => '2026-03-10 09:39:00',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-25 10:30:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            4 => [
                'id' => 6,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Smart tech case study',
                'slug' => 'smart-tech-case-study',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => 'center',
                'overlaysize' => 'full',
                'overlaytransp' => '0',
                'overlaycolor' => 'black',
                'urltext' => null,
                'urltitle' => null,
                'url' => null,
                'payoff' => '<p>Adipiscing quis a at ligula. Gravida gravida diam rhoncus cursus in. Turpis sagittis tempor gravida phasellus sapien. Faucibus donec consectetur sed id sit nisl.</p>',
                'subtitle' => 'Data Analytics Company',
                'captiontype' => null,
                'type' => 'payoff',
                'created_at' => '2025-08-25 10:35:39',
                'updated_at' => '2026-03-10 09:38:44',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2025-08-25 10:35:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
            5 => [
                'id' => 7,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => null,
                'title' => 'Pagetitle nr 1',
                'slug' => 'pagetitle-nr-1',
                'slug_lock' => 0,
                'lead' => null,
                'body' => null,
                'textposition' => null,
                'overlaysize' => null,
                'overlaytransp' => null,
                'overlaycolor' => null,
                'urltext' => null,
                'urltitle' => null,
                'url' => null,
                'payoff' => null,
                'subtitle' => null,
                'captiontype' => null,
                'type' => 'image',
                'created_at' => '2026-03-19 10:45:22',
                'updated_at' => '2026-03-20 08:57:58',
                'deleted_at' => null,
                'publish' => 1,
                'publish_from' => '2026-03-19 10:44:00',
                'publish_expire' => 0,
                'publish_to' => null,
                'position' => null,
                'cgroup' => null,
                'locked_at' => null,
                'locked_by' => null,
            ],
        ]);

    }
}
