<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraResourceEntityCustomFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_resource_entity_custom_fields')->delete();

        \DB::table('lara_resource_entity_custom_fields')->insert(array (
            0 =>
            array (
                'id' => 52,
                'entity_id' => 2,
                'title' => 'source',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'source',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            1 =>
            array (
                'id' => 55,
                'entity_id' => 3,
                'title' => 'First name',
                'field_hook' => 'before-title',
                'field_type' => 'string',
                'field_name' => 'first_name',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            2 =>
            array (
                'id' => 56,
                'entity_id' => 3,
                'title' => 'Middle Name',
                'field_hook' => 'before-title',
                'field_type' => 'string',
                'field_name' => 'middle_name',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 120,
            ),
            3 =>
            array (
                'id' => 57,
                'entity_id' => 3,
                'title' => 'Role',
                'field_hook' => 'after-slug',
                'field_type' => 'string',
                'field_name' => 'role',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 1,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 230,
            ),
            4 =>
            array (
                'id' => 58,
                'entity_id' => 3,
                'title' => 'Email',
                'field_hook' => 'after-last',
                'field_type' => 'email',
                'field_name' => 'email',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 410,
            ),
            5 =>
            array (
                'id' => 59,
                'entity_id' => 3,
                'title' => 'Facebook',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'facebook',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 420,
            ),
            6 =>
            array (
                'id' => 60,
                'entity_id' => 3,
                'title' => 'Twitter',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'twitter',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 430,
            ),
            7 =>
            array (
                'id' => 61,
                'entity_id' => 3,
                'title' => 'LinkedIn',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'linkedin',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 440,
            ),
            8 =>
            array (
                'id' => 64,
                'entity_id' => 42,
                'title' => 'type',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["image","caption","payoff"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            9 =>
            array (
                'id' => 65,
                'entity_id' => 42,
                'title' => 'captiontype',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'captiontype',
                'field_name_temp' => NULL,
                'field_options' => '["block","fade"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'captiontype',
                'rule_operator' => 'isequal',
                'rule_value' => 'caption',
                'sort_order' => 120,
            ),
            10 =>
            array (
                'id' => 66,
                'entity_id' => 42,
                'title' => 'subtitle',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'subtitle',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 130,
            ),
            11 =>
            array (
                'id' => 67,
                'entity_id' => 42,
                'title' => 'payoff',
                'field_hook' => 'after-last',
                'field_type' => 'richeditor',
                'field_name' => 'payoff',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 140,
            ),
            12 =>
            array (
                'id' => 68,
                'entity_id' => 42,
                'title' => 'url',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'url',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 150,
            ),
            13 =>
            array (
                'id' => 69,
                'entity_id' => 42,
                'title' => 'urltitle',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'urltitle',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 160,
            ),
            14 =>
            array (
                'id' => 70,
                'entity_id' => 42,
                'title' => 'urltext',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'urltext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 170,
            ),
            15 =>
            array (
                'id' => 71,
                'entity_id' => 42,
                'title' => 'overlaycolor',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaycolor',
                'field_name_temp' => NULL,
                'field_options' => '["black","white","brand1","brand2","brand3"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 180,
            ),
            16 =>
            array (
                'id' => 72,
                'entity_id' => 42,
                'title' => 'overlaytransp',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaytransp',
                'field_name_temp' => NULL,
                'field_options' => '["0","10","20","30","40","50","60","70","80","90"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 190,
            ),
            17 =>
            array (
                'id' => 73,
                'entity_id' => 42,
                'title' => 'overlaysize',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaysize',
                'field_name_temp' => NULL,
                'field_options' => '["full","block"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 200,
            ),
            18 =>
            array (
                'id' => 74,
                'entity_id' => 42,
                'title' => 'textposition',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'textposition',
                'field_name_temp' => NULL,
                'field_options' => '["center","left","right"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'payoff',
                'sort_order' => 210,
            ),
            19 =>
            array (
                'id' => 82,
                'entity_id' => 43,
                'title' => 'name',
                'field_hook' => 'default',
                'field_type' => 'string',
                'field_name' => 'name',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            20 =>
            array (
                'id' => 85,
                'entity_id' => 43,
                'title' => 'email',
                'field_hook' => 'default',
                'field_type' => 'email',
                'field_name' => 'email',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            21 =>
            array (
                'id' => 86,
                'entity_id' => 43,
                'title' => 'telephone',
                'field_hook' => 'default',
                'field_type' => 'string',
                'field_name' => 'telephone',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            22 =>
            array (
                'id' => 87,
                'entity_id' => 43,
                'title' => 'comment',
                'field_hook' => 'default',
                'field_type' => 'textarea',
                'field_name' => 'comment',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            23 =>
            array (
                'id' => 94,
                'entity_id' => 1,
                'title' => 'ishome',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'ishome',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'hidden',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            24 =>
            array (
                'id' => 95,
                'entity_id' => 1,
                'title' => 'menuroute',
                'field_hook' => 'before-title',
                'field_type' => 'string',
                'field_name' => 'menuroute',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 1,
                'rule_state' => 'hidden',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            25 =>
            array (
                'id' => 96,
                'entity_id' => 44,
                'title' => 'startdate',
                'field_hook' => 'after-slug',
                'field_type' => 'date',
                'field_name' => 'startdate',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            26 =>
            array (
                'id' => 97,
                'entity_id' => 44,
                'title' => 'starttime',
                'field_hook' => 'after-slug',
                'field_type' => 'time',
                'field_name' => 'starttime',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 120,
            ),
            27 =>
            array (
                'id' => 98,
                'entity_id' => 44,
                'title' => 'enddate',
                'field_hook' => 'after-slug',
                'field_type' => 'date',
                'field_name' => 'enddate',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 130,
            ),
            28 =>
            array (
                'id' => 99,
                'entity_id' => 44,
                'title' => 'endtime',
                'field_hook' => 'after-slug',
                'field_type' => 'time',
                'field_name' => 'endtime',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 140,
            ),
            29 =>
            array (
                'id' => 100,
                'entity_id' => 52,
                'title' => 'hook',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'hook',
                'field_name_temp' => NULL,
                'field_options' => '["content_top","content_bottom","home1","home2","home3","home4","home5","home6","home7","home8","home9","home10","footer1","footer2","footer3","footer4"]',
                'is_required' => 1,
                'is_filter' => 1,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            30 =>
            array (
                'id' => 101,
                'entity_id' => 52,
                'title' => 'type',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["text","icon","feature","module"]',
                'is_required' => 1,
                'is_filter' => 1,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 130,
            ),
            31 =>
            array (
                'id' => 102,
                'entity_id' => 52,
                'title' => 'resource_slug',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'resource_slug',
                'field_name_temp' => NULL,
                'field_options' => '["get_entity_resources"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 131,
            ),
            32 =>
            array (
                'id' => 103,
                'entity_id' => 52,
                'title' => 'resource_term',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'resource_term',
                'field_name_temp' => NULL,
                'field_options' => '["get_entity_terms"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 132,
            ),
            33 =>
            array (
                'id' => 104,
                'entity_id' => 52,
                'title' => 'is_global',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'is_global',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 120,
            ),
            34 =>
            array (
                'id' => 105,
                'entity_id' => 52,
                'title' => 'image_required',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'image_required',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 133,
            ),
            35 =>
            array (
                'id' => 106,
                'entity_id' => 52,
                'title' => 'max_items',
                'field_hook' => 'after-title',
                'field_type' => 'number',
                'field_name' => 'max_items',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'module',
                'sort_order' => 134,
            ),
            36 =>
            array (
                'id' => 107,
                'entity_id' => 52,
                'title' => 'iconclass',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'iconclass',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'icon',
                'sort_order' => 141,
            ),
            37 =>
            array (
                'id' => 108,
                'entity_id' => 52,
                'title' => 'iconalign',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'iconalign',
                'field_name_temp' => NULL,
                'field_options' => '["top","left","right"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isequal',
                'rule_value' => 'icon',
                'sort_order' => 142,
            ),
            38 =>
            array (
                'id' => 109,
                'entity_id' => 52,
                'title' => 'linktext',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'linktext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isnotequal',
                'rule_value' => 'module',
                'sort_order' => 150,
            ),
            39 =>
            array (
                'id' => 110,
                'entity_id' => 52,
                'title' => 'linkurl',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'linkurl',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 1,
                'rule_state' => 'enabledif',
                'rule_field' => 'type',
                'rule_operator' => 'isnotequal',
                'rule_value' => 'module',
                'sort_order' => 155,
            ),
            40 =>
            array (
                'id' => 111,
                'entity_id' => 52,
                'title' => 'usecache',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'usecache',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 125,
            ),
            41 =>
            array (
                'id' => 112,
                'entity_id' => 52,
                'title' => 'sortorder',
                'field_hook' => 'after-title',
                'field_type' => 'number',
                'field_name' => 'sortorder',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 126,
            ),
            42 =>
            array (
                'id' => 113,
                'entity_id' => 52,
                'title' => 'template',
                'field_hook' => 'after-title',
                'field_type' => 'select',
                'field_name' => 'template',
                'field_name_temp' => NULL,
                'field_options' => '["get_widget_templates"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 160,
            ),
            43 =>
            array (
                'id' => 114,
                'entity_id' => 59,
                'title' => 'linktext',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'linktext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            44 =>
            array (
                'id' => 115,
                'entity_id' => 59,
                'title' => 'linkurl',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'linkurl',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            45 =>
            array (
                'id' => 116,
                'entity_id' => 59,
                'title' => 'hook',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'hook',
                'field_name_temp' => NULL,
                'field_options' => '["contact","newsletter"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            46 =>
            array (
                'id' => 117,
                'entity_id' => 59,
                'title' => 'type',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'type',
                'field_name_temp' => NULL,
                'field_options' => '["solid","image","parallax"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            47 =>
            array (
                'id' => 118,
                'entity_id' => 59,
                'title' => 'overlaycolor',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaycolor',
                'field_name_temp' => NULL,
                'field_options' => '["black","brand"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            48 =>
            array (
                'id' => 119,
                'entity_id' => 59,
                'title' => 'overlaytransp',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'overlaytransp',
                'field_name_temp' => NULL,
                'field_options' => '["0","10","20","30","40","50","60","70","80","90"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            49 =>
            array (
                'id' => 120,
                'entity_id' => 62,
                'title' => 'stars',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'stars',
                'field_name_temp' => NULL,
                'field_options' => '["1","2","3","4","5"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 30,
            ),
            50 =>
            array (
                'id' => 121,
                'entity_id' => 62,
                'title' => 'role',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'role',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 10,
            ),
            51 =>
            array (
                'id' => 122,
                'entity_id' => 62,
                'title' => 'quoteshort',
                'field_hook' => 'after-title',
                'field_type' => 'string',
                'field_name' => 'quoteshort',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 20,
            ),
            52 =>
            array (
                'id' => 123,
                'entity_id' => 63,
                'title' => 'url',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'url',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            53 =>
            array (
                'id' => 124,
                'entity_id' => 69,
                'title' => 'myname',
                'field_hook' => 'default',
                'field_type' => 'string',
                'field_name' => 'myname',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 10,
            ),
            54 =>
            array (
                'id' => 125,
                'entity_id' => 69,
                'title' => 'myemail',
                'field_hook' => 'default',
                'field_type' => 'email',
                'field_name' => 'myemail',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 1,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 20,
            ),
            55 =>
            array (
                'id' => 126,
                'entity_id' => 69,
                'title' => 'myboolean',
                'field_hook' => 'default',
                'field_type' => 'toggle',
                'field_name' => 'myboolean',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 30,
            ),
            56 =>
            array (
                'id' => 127,
                'entity_id' => 69,
                'title' => 'mycomment',
                'field_hook' => 'default',
                'field_type' => 'textarea',
                'field_name' => 'mycomment',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 40,
            ),
            57 =>
            array (
                'id' => 128,
                'entity_id' => 69,
                'title' => 'myselect',
                'field_hook' => 'default',
                'field_type' => 'select',
                'field_name' => 'myselect',
                'field_name_temp' => NULL,
                'field_options' => '["one","two","three"]',
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 50,
            ),
            58 =>
            array (
                'id' => 129,
                'entity_id' => 69,
                'title' => 'myradio',
                'field_hook' => 'default',
                'field_type' => 'radio',
                'field_name' => 'myradio',
                'field_name_temp' => NULL,
                'field_options' => '["four","five","six"]',
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 60,
            ),
            59 =>
            array (
                'id' => 130,
                'entity_id' => 69,
                'title' => 'mydate',
                'field_hook' => 'default',
                'field_type' => 'date',
                'field_name' => 'mydate',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 1,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 70,
            ),
            60 =>
            array (
                'id' => 133,
                'entity_id' => 2,
                'title' => 'sticky',
                'field_hook' => 'after-title',
                'field_type' => 'toggle',
                'field_name' => 'sticky',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            61 =>
            array (
                'id' => 134,
                'entity_id' => 41,
                'title' => 'Geo Location',
                'field_hook' => 'after-last',
                'field_type' => 'geolocation',
                'field_name' => 'geolocation',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
            62 =>
            array (
                'id' => 135,
                'entity_id' => 70,
                'title' => 'mystring',
                'field_hook' => 'after-last',
                'field_type' => 'string',
                'field_name' => 'mystring',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 110,
            ),
            63 =>
            array (
                'id' => 136,
                'entity_id' => 70,
                'title' => 'myemail',
                'field_hook' => 'after-last',
                'field_type' => 'email',
                'field_name' => 'myemail',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 120,
            ),
            64 =>
            array (
                'id' => 137,
                'entity_id' => 70,
                'title' => 'mytext',
                'field_hook' => 'after-last',
                'field_type' => 'text',
                'field_name' => 'mytext',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 130,
            ),
            65 =>
            array (
                'id' => 138,
                'entity_id' => 70,
                'title' => 'mynumber',
                'field_hook' => 'after-last',
                'field_type' => 'number',
                'field_name' => 'mynumber',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 140,
            ),
            66 =>
            array (
                'id' => 139,
                'entity_id' => 70,
                'title' => 'mytextarea',
                'field_hook' => 'after-last',
                'field_type' => 'textarea',
                'field_name' => 'mytextarea',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 150,
            ),
            67 =>
            array (
                'id' => 149,
                'entity_id' => 70,
                'title' => 'mydecimal',
                'field_hook' => 'after-last',
                'field_type' => 'decimal_16_4',
                'field_name' => 'mydecimal',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 250,
            ),
            68 =>
            array (
                'id' => 150,
                'entity_id' => 70,
                'title' => 'mydate',
                'field_hook' => 'after-last',
                'field_type' => 'date',
                'field_name' => 'mydate',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 260,
            ),
            69 =>
            array (
                'id' => 151,
                'entity_id' => 70,
                'title' => 'mytime',
                'field_hook' => 'after-last',
                'field_type' => 'time',
                'field_name' => 'mytime',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 270,
            ),
            70 =>
            array (
                'id' => 152,
                'entity_id' => 70,
                'title' => 'mydatetime',
                'field_hook' => 'after-last',
                'field_type' => 'datetime',
                'field_name' => 'mydatetime',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 280,
            ),
            71 =>
            array (
                'id' => 154,
                'entity_id' => 70,
                'title' => 'myselect',
                'field_hook' => 'after-last',
                'field_type' => 'select',
                'field_name' => 'myselect_2',
                'field_name_temp' => NULL,
                'field_options' => '["one","two","three"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 160,
            ),
            72 =>
            array (
                'id' => 155,
                'entity_id' => 70,
                'title' => 'mymultiselect',
                'field_hook' => 'after-last',
                'field_type' => 'multiselect',
                'field_name' => 'mymultiselect',
                'field_name_temp' => NULL,
                'field_options' => '["four","five","six"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 170,
            ),
            73 =>
            array (
                'id' => 156,
                'entity_id' => 70,
                'title' => 'mytagsinput',
                'field_hook' => 'after-last',
                'field_type' => 'tagsinput',
                'field_name' => 'mytagsinput',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 180,
            ),
            74 =>
            array (
                'id' => 157,
                'entity_id' => 70,
                'title' => 'mytoggle',
                'field_hook' => 'after-last',
                'field_type' => 'toggle',
                'field_name' => 'mytoggle',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 190,
            ),
            75 =>
            array (
                'id' => 159,
                'entity_id' => 70,
                'title' => 'mytogglebuttons',
                'field_hook' => 'after-last',
                'field_type' => 'togglebuttons',
                'field_name' => 'mytogglebuttons',
                'field_name_temp' => NULL,
                'field_options' => '["one","two","three"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 200,
            ),
            76 =>
            array (
                'id' => 160,
                'entity_id' => 70,
                'title' => 'mymultitogglebuttons',
                'field_hook' => 'after-last',
                'field_type' => 'multitogglebuttons',
                'field_name' => 'mymultitogglebuttons',
                'field_name_temp' => NULL,
                'field_options' => '["four","five","six"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 210,
            ),
            77 =>
            array (
                'id' => 161,
                'entity_id' => 70,
                'title' => 'mycheckboxlist',
                'field_hook' => 'after-last',
                'field_type' => 'checkboxlist',
                'field_name' => 'mycheckboxlist',
                'field_name_temp' => NULL,
                'field_options' => '["four","five","six"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 230,
            ),
            78 =>
            array (
                'id' => 162,
                'entity_id' => 70,
                'title' => 'mycheckbox',
                'field_hook' => 'after-last',
                'field_type' => 'checkbox',
                'field_name' => 'mycheckbox',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 220,
            ),
            79 =>
            array (
                'id' => 163,
                'entity_id' => 70,
                'title' => 'myradio',
                'field_hook' => 'after-last',
                'field_type' => 'radio',
                'field_name' => 'myradio',
                'field_name_temp' => NULL,
                'field_options' => '["seven","eight","nine"]',
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 230,
            ),
            80 =>
            array (
                'id' => 164,
                'entity_id' => 70,
                'title' => 'mycolor',
                'field_hook' => 'after-last',
                'field_type' => 'colorpicker',
                'field_name' => 'mycolor',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => 240,
            ),
            81 =>
            array (
                'id' => 165,
                'entity_id' => 73,
                'title' => 'geolocation',
                'field_hook' => 'after-last',
                'field_type' => 'geolocation',
                'field_name' => 'geolocation',
                'field_name_temp' => NULL,
                'field_options' => NULL,
                'is_required' => 0,
                'is_filter' => 0,
                'show_in_list' => 0,
                'conditional' => 0,
                'rule_state' => 'enabled',
                'rule_field' => NULL,
                'rule_operator' => NULL,
                'rule_value' => NULL,
                'sort_order' => NULL,
            ),
        ));


    }
}