<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraObjectImagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_object_images')->delete();

        \DB::table('lara_object_images')->insert(array (
            0 =>
            array (
                'id' => 92,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 22,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121310-09.jpg", "featured_original": "09.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            1 =>
            array (
                'id' => 93,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2062,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            2 =>
            array (
                'id' => 94,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2068,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            3 =>
            array (
                'id' => 95,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903132149-01.jpg", "featured_original": "01.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            4 =>
            array (
                'id' => 96,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135042-02.jpg", "featured_original": "02.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            5 =>
            array (
                'id' => 97,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": "Lorem ipsum", "featured_filename": "pages/20250824184158-20230426172552-video-cover.jpg", "featured_original": "20230426172552-video-cover.jpg", "featured_seo_title": "Video Cover", "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => '[{"hero_caption": null, "hero_seo_alt": null, "hero_filename": "pages/20250904115441-cover.jpg", "hero_original": "cover.jpg", "hero_hero_size": 2, "hero_seo_title": null}]',
                'icon' => NULL,
                'gallery' => '[{"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-01.jpg", "gallery_original": "tech-01.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-05.jpg", "gallery_original": "tech-05.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-03.jpg", "gallery_original": "tech-03.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-06.png", "gallery_original": "tech-06.png", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-04.jpg", "gallery_original": "tech-04.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-02.jpg", "gallery_original": "tech-02.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-07.jpg", "gallery_original": "tech-07.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907102938-tech-08.jpg", "gallery_original": "tech-08.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "pages/20250907105440-01b.jpg", "gallery_original": "01b.jpg", "gallery_seo_title": null}]',
                'gallery_upload' => '[]',
                'image_count' => 11,
            ),
            6 =>
            array (
                'id' => 98,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 23,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121559-office-at-night.jpg", "featured_original": "office-at-night.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            7 =>
            array (
                'id' => 99,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2071,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            8 =>
            array (
                'id' => 100,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2076,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            9 =>
            array (
                'id' => 101,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2078,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            10 =>
            array (
                'id' => 102,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135136-03.jpg", "featured_original": "03.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            11 =>
            array (
                'id' => 103,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 4,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135152-04.jpg", "featured_original": "04.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            12 =>
            array (
                'id' => 104,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135212-05.jpg", "featured_original": "05.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            13 =>
            array (
                'id' => 105,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 6,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135241-06.jpg", "featured_original": "06.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            14 =>
            array (
                'id' => 106,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 7,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135310-07.jpg", "featured_original": "07.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            15 =>
            array (
                'id' => 107,
                'entity_type' => 'Lara\\App\\Models\\Team',
                'entity_id' => 8,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "teams/20250903135329-08.jpg", "featured_original": "08.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            16 =>
            array (
                'id' => 108,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 27,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121347-03.jpg", "featured_original": "03.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            17 =>
            array (
                'id' => 110,
                'entity_type' => 'Lara\\App\\Models\\Event',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "events/20250914181725-laracon-us.jpg", "featured_original": "laracon-us.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            18 =>
            array (
                'id' => 111,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2085,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            19 =>
            array (
                'id' => 112,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2086,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            20 =>
            array (
                'id' => 113,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2087,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            21 =>
            array (
                'id' => 114,
                'entity_type' => 'Lara\\App\\Models\\Event',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "events/20250914181620-laracon-eu.jpg", "featured_original": "laracon-eu.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            22 =>
            array (
                'id' => 115,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 17,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            23 =>
            array (
                'id' => 116,
                'entity_type' => 'Lara\\Common\\Models\\Widget',
                'entity_id' => 1,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            24 =>
            array (
                'id' => 117,
                'entity_type' => 'Lara\\Common\\Models\\Widget',
                'entity_id' => 2,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            25 =>
            array (
                'id' => 118,
                'entity_type' => 'Lara\\App\\Models\\Cta',
                'entity_id' => 2,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            26 =>
            array (
                'id' => 120,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 31,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825120828-01.jpg", "featured_original": "01.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[{"thumb_caption": null, "thumb_seo_alt": null, "thumb_filename": "blogs/20250903164334-meeting-detail.jpg", "thumb_original": "meeting-detail.jpg", "thumb_seo_title": null}]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 2,
            ),
            27 =>
            array (
                'id' => 121,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 19,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            28 =>
            array (
                'id' => 122,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 30,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121705-06.jpg", "featured_original": "06.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            29 =>
            array (
                'id' => 123,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2088,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            30 =>
            array (
                'id' => 124,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2089,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            31 =>
            array (
                'id' => 125,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2091,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            32 =>
            array (
                'id' => 126,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2092,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            33 =>
            array (
                'id' => 127,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2093,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            34 =>
            array (
                'id' => 128,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2094,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            35 =>
            array (
                'id' => 129,
                'entity_type' => 'Lara\\App\\Models\\Service',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "services/20250822184842-01-light.png", "featured_original": "01-light.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            36 =>
            array (
                'id' => 130,
                'entity_type' => 'Lara\\App\\Models\\Service',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "services/20250822184810-02-light.png", "featured_original": "02-light.png", "featured_seo_title": null}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            37 =>
            array (
                'id' => 131,
                'entity_type' => 'Lara\\App\\Models\\Service',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "services/20250822185002-03-light.png", "featured_original": "03-light.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            38 =>
            array (
                'id' => 132,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824124157-11.jpg", "featured_original": "11.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            39 =>
            array (
                'id' => 133,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824124521-14.jpg", "featured_original": "14.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            40 =>
            array (
                'id' => 134,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824124703-10.jpg", "featured_original": "10.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            41 =>
            array (
                'id' => 135,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 4,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824124939-14.jpg", "featured_original": "14.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            42 =>
            array (
                'id' => 136,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824125150-13.jpg", "featured_original": "13.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            43 =>
            array (
                'id' => 137,
                'entity_type' => 'Lara\\App\\Models\\Testimonial',
                'entity_id' => 6,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "testimonials/20250824125319-11.jpg", "featured_original": "11.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            44 =>
            array (
                'id' => 138,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2099,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            45 =>
            array (
                'id' => 139,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131527-brand-01.png", "featured_original": "brand-01.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            46 =>
            array (
                'id' => 140,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131551-brand-02.png", "featured_original": "brand-02.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            47 =>
            array (
                'id' => 141,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131607-brand-03.png", "featured_original": "brand-03.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            48 =>
            array (
                'id' => 142,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 4,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131627-brand-04.png", "featured_original": "brand-04.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            49 =>
            array (
                'id' => 143,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131643-brand-05.png", "featured_original": "brand-05.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            50 =>
            array (
                'id' => 144,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 6,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131703-brand-06.png", "featured_original": "brand-06.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            51 =>
            array (
                'id' => 145,
                'entity_type' => 'Lara\\App\\Models\\Portfolio',
                'entity_id' => 7,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "portfolios/20250824131723-brand-07.png", "featured_original": "brand-07.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            52 =>
            array (
                'id' => 146,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "sliders/20250825075214-meeting-with-a-view.jpg", "featured_original": "meeting-with-a-view.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            53 =>
            array (
                'id' => 147,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "sliders/20250825075242-meeting-detail.jpg", "featured_original": "meeting-detail.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            54 =>
            array (
                'id' => 148,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_id' => 4,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "sliders/20250825075308-office-at-night.jpg", "featured_original": "office-at-night.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            55 =>
            array (
                'id' => 149,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "pages/20250825085842-istock-519363909.jpg", "featured_original": "istock-519363909.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            56 =>
            array (
                'id' => 150,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 3,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "widgets/20250825092449-01.png", "featured_original": "01.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            57 =>
            array (
                'id' => 151,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 4,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "widgets/20250825092920-02.png", "featured_original": "02.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            58 =>
            array (
                'id' => 152,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "widgets/20250825093024-03.png", "featured_original": "03.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            59 =>
            array (
                'id' => 153,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 6,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "widgets/20250825093238-04.png", "featured_original": "04.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            60 =>
            array (
                'id' => 154,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_id' => 5,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "sliders/20250825103145-case-study01.jpg", "featured_original": "case-study01.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            61 =>
            array (
                'id' => 155,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_id' => 6,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "sliders/20250825103625-case-study-2.jpg", "featured_original": "case-study-2.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            62 =>
            array (
                'id' => 156,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 7,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "widgets/20250825112412-lara-logo-2023.png", "featured_original": "lara-logo-2023.png", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 1,
            ),
            63 =>
            array (
                'id' => 157,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 8,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            64 =>
            array (
                'id' => 158,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 9,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            65 =>
            array (
                'id' => 159,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 29,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121232-05.jpg", "featured_original": "05.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            66 =>
            array (
                'id' => 160,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 26,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121418-02.jpg", "featured_original": "02.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            67 =>
            array (
                'id' => 161,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 25,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121508-meeting-with-a-view.jpg", "featured_original": "meeting-with-a-view.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            68 =>
            array (
                'id' => 162,
                'entity_type' => 'Lara\\App\\Models\\Blog',
                'entity_id' => 24,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "blogs/20250825121532-meeting-detail.jpg", "featured_original": "meeting-detail.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            69 =>
            array (
                'id' => 163,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2102,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            70 =>
            array (
                'id' => 164,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2105,
                'featured' => NULL,
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            71 =>
            array (
                'id' => 165,
                'entity_type' => 'Lara\\App\\Models\\Gallery',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "galleries/20250829123138-06.jpg", "featured_original": "06.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[{"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-01.jpg", "gallery_original": "01.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-02.jpg", "gallery_original": "02.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-03.jpg", "gallery_original": "03.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-04.jpg", "gallery_original": "04.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-05.jpg", "gallery_original": "05.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123002-06.jpg", "gallery_original": "06.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123138-07.jpg", "gallery_original": "07.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123138-08.jpg", "gallery_original": "08.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123138-09.jpg", "gallery_original": "09.jpg", "gallery_seo_title": null}]',
                'gallery_upload' => '[]',
                'image_count' => 10,
            ),
            72 =>
            array (
                'id' => 166,
                'entity_type' => 'Lara\\App\\Models\\Gallery',
                'entity_id' => 2,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "galleries/20250829123623-tech-04.jpg", "featured_original": "tech-04.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[{"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-01.jpg", "gallery_original": "tech-01.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-02.jpg", "gallery_original": "tech-02.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-04.jpg", "gallery_original": "tech-04.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-03.jpg", "gallery_original": "tech-03.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-05.jpg", "gallery_original": "tech-05.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-06.png", "gallery_original": "tech-06.png", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-07.jpg", "gallery_original": "tech-07.jpg", "gallery_seo_title": null}, {"gallery_caption": null, "gallery_seo_alt": null, "gallery_filename": "galleries/20250829123505-tech-08.jpg", "gallery_original": "tech-08.jpg", "gallery_seo_title": null}]',
                'gallery_upload' => '[]',
                'image_count' => 9,
            ),
            73 =>
            array (
                'id' => 167,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 25,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            74 =>
            array (
                'id' => 168,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 1,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            75 =>
            array (
                'id' => 169,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 14,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "pages/20250903135948-hero-bg.jpg", "featured_original": "hero-bg.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 1,
            ),
            76 =>
            array (
                'id' => 170,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 34,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            77 =>
            array (
                'id' => 171,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 35,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            78 =>
            array (
                'id' => 172,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 36,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            79 =>
            array (
                'id' => 173,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2060,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "tags/20250903172438-olympia-hilversum.jpg", "featured_original": "olympia-hilversum.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[]',
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => NULL,
            ),
            80 =>
            array (
                'id' => 174,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 37,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            81 =>
            array (
                'id' => 175,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 2,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            82 =>
            array (
                'id' => 176,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 10,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            83 =>
            array (
                'id' => 177,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 38,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            84 =>
            array (
                'id' => 178,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 40,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            85 =>
            array (
                'id' => 179,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 41,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            86 =>
            array (
                'id' => 180,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 11,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            87 =>
            array (
                'id' => 181,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 12,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            88 =>
            array (
                'id' => 182,
                'entity_type' => 'Lara\\Common\\Models\\LaraWidget',
                'entity_id' => 13,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => 0,
            ),
            89 =>
            array (
                'id' => 183,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_id' => 42,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            90 =>
            array (
                'id' => 184,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 1,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            91 =>
            array (
                'id' => 185,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 2,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            92 =>
            array (
                'id' => 186,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 3,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            93 =>
            array (
                'id' => 187,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 5,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            94 =>
            array (
                'id' => 188,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 9,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            95 =>
            array (
                'id' => 189,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 10,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            96 =>
            array (
                'id' => 190,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 11,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            97 =>
            array (
                'id' => 191,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 12,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            98 =>
            array (
                'id' => 192,
                'entity_type' => 'Lara\\App\\Models\\Product',
                'entity_id' => 14,
                'featured' => '[]',
                'thumb' => '[]',
                'hero' => '[]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 0,
            ),
            99 =>
            array (
                'id' => 193,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2110,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            100 =>
            array (
                'id' => 194,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_id' => 2112,
                'featured' => '[]',
                'thumb' => NULL,
                'hero' => NULL,
                'icon' => NULL,
                'gallery' => NULL,
                'gallery_upload' => NULL,
                'image_count' => NULL,
            ),
            101 =>
            array (
                'id' => 195,
                'entity_type' => 'Lara\\App\\Models\\City',
                'entity_id' => 1,
                'featured' => '[{"featured_caption": null, "featured_seo_alt": null, "featured_filename": "cities/20251021131450-haarlem-sky.jpg", "featured_original": "haarlem-sky.jpg", "featured_seo_title": null, "featured_prevent_cropping": false}]',
                'thumb' => '[{"thumb_caption": null, "thumb_seo_alt": null, "thumb_filename": "cities/20251021131510-hoge-hout-by-night.jpg", "thumb_original": "hoge-hout-by-night.jpg", "thumb_seo_title": null}]',
                'hero' => '[{"hero_caption": null, "hero_seo_alt": null, "hero_filename": "cities/20251021131529-olympia-hilversum.jpg", "hero_original": "olympia-hilversum.jpg", "hero_hero_size": null, "hero_seo_title": null}]',
                'icon' => NULL,
                'gallery' => '[]',
                'gallery_upload' => '[]',
                'image_count' => 3,
            ),
        ));


    }
}