<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraSysSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_sys_settings')->delete();

        \DB::table('lara_sys_settings')->insert(array (
            0 =>
            array (
                'id' => 101,
                'title' => 'Company Name',
                'cgroup' => 'company',
                'key' => 'company_name',
                'value' => 'Firmaq Media',
                'locked_by_admin' => 0,
                'position' => 2,
                'created_at' => '2017-10-17 15:44:37',
                'updated_at' => '2024-10-25 15:33:18',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 102,
                'title' => 'Company Street',
                'cgroup' => 'company',
                'key' => 'company_street',
                'value' => 'Schipholweg',
                'locked_by_admin' => 0,
                'position' => 4,
                'created_at' => '2017-10-17 17:37:10',
                'updated_at' => '2023-04-16 20:18:56',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 103,
                'title' => 'Company Email Address',
                'cgroup' => 'company',
                'key' => 'company_email',
                'value' => 'info@firmaq.nl',
                'locked_by_admin' => 0,
                'position' => 3,
                'created_at' => '2017-10-17 17:53:53',
                'updated_at' => '2023-10-14 16:28:36',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 105,
                'title' => 'Translation File Sync',
                'cgroup' => 'system',
                'key' => 'translation_file_sync',
                'value' => '2025-03-07 10:38:57',
                'locked_by_admin' => 0,
                'position' => 1,
                'created_at' => '2017-10-20 12:59:00',
                'updated_at' => '2025-03-07 10:38:57',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 106,
                'title' => 'Company Street Nr',
                'cgroup' => 'company',
                'key' => 'company_street_nr',
                'value' => '66',
                'locked_by_admin' => 0,
                'position' => 5,
                'created_at' => '2018-01-22 09:48:07',
                'updated_at' => '2023-02-10 20:29:45',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 107,
                'title' => 'Company Postal Code',
                'cgroup' => 'company',
                'key' => 'company_pcode',
                'value' => '2035LB',
                'locked_by_admin' => 0,
                'position' => 6,
                'created_at' => '2018-01-24 12:41:38',
                'updated_at' => '2023-10-13 16:30:42',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 108,
                'title' => 'Company City',
                'cgroup' => 'company',
                'key' => 'company_city',
                'value' => 'Haarlem',
                'locked_by_admin' => 0,
                'position' => 7,
                'created_at' => '2018-01-24 12:42:00',
                'updated_at' => '2023-02-10 20:30:06',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 109,
                'title' => 'Company Telephone',
                'cgroup' => 'company',
                'key' => 'company_telephone',
                'value' => '085 2006261',
                'locked_by_admin' => 0,
                'position' => 10,
                'created_at' => '2018-01-24 12:42:43',
                'updated_at' => '2021-11-10 17:08:09',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 110,
                'title' => 'Company Region',
                'cgroup' => 'company',
                'key' => 'company_region',
                'value' => 'Noord-Holland',
                'locked_by_admin' => 0,
                'position' => 8,
                'created_at' => '2018-01-24 12:43:29',
                'updated_at' => '2019-12-18 12:52:15',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 111,
                'title' => 'Company Country',
                'cgroup' => 'company',
                'key' => 'company_country',
                'value' => 'Nederland',
                'locked_by_admin' => 0,
                'position' => 9,
                'created_at' => '2018-01-24 12:43:50',
                'updated_at' => '2018-01-24 12:43:58',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 112,
                'title' => 'google_analytics_sync',
                'cgroup' => 'system',
                'key' => 'google_analytics_sync',
                'value' => '2024-10-25 15:27:01',
                'locked_by_admin' => 0,
                'position' => 11,
                'created_at' => '2018-05-30 14:14:21',
                'updated_at' => '2024-10-25 15:27:01',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 113,
                'title' => 'Google Analytics 4 ID',
                'cgroup' => 'company',
                'key' => 'ga4_id',
                'value' => 'G-P2VMZDGC1Z',
                'locked_by_admin' => 0,
                'position' => 23,
                'created_at' => '2018-05-25 12:00:00',
                'updated_at' => '2023-09-21 11:15:58',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 114,
                'title' => 'AddThis ID',
                'cgroup' => 'company',
                'key' => 'addthis_id',
                'value' => 'ra-',
                'locked_by_admin' => 0,
                'position' => 24,
                'created_at' => '2018-05-25 12:00:00',
                'updated_at' => '2023-02-10 20:28:37',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 115,
                'title' => 'Lara DB Version',
                'cgroup' => 'system',
                'key' => 'lara_db_version',
                'value' => '8.5.14',
                'locked_by_admin' => 0,
                'position' => 25,
                'created_at' => '2018-06-12 11:18:52',
                'updated_at' => '2025-01-20 10:34:45',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 116,
                'title' => 'Company Latitude',
                'cgroup' => 'company',
                'key' => 'company_latitude',
                'value' => '52.3700304',
                'locked_by_admin' => 0,
                'position' => 26,
                'created_at' => '2018-06-18 14:01:02',
                'updated_at' => '2023-03-17 15:48:11',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 117,
                'title' => 'Company Longitude',
                'cgroup' => 'company',
                'key' => 'company_longitude',
                'value' => '4.6454777',
                'locked_by_admin' => 0,
                'position' => 27,
                'created_at' => '2018-06-18 14:01:18',
                'updated_at' => '2023-03-17 15:48:11',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 118,
                'title' => 'Company Url',
                'cgroup' => 'company',
                'key' => 'company_url',
                'value' => NULL,
                'locked_by_admin' => 0,
                'position' => 28,
                'created_at' => '2018-06-18 14:01:31',
                'updated_at' => '2023-02-10 20:27:48',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 119,
                'title' => 'Google Maps Zoom',
                'cgroup' => 'general',
                'key' => 'google_maps_zoom',
                'value' => '15',
                'locked_by_admin' => 0,
                'position' => 29,
                'created_at' => '2018-06-18 14:04:34',
                'updated_at' => '2018-06-18 14:07:50',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 120,
                'title' => 'lara_cleanup_orphans',
                'cgroup' => 'system',
                'key' => 'lara_cleanup_orphans',
                'value' => '2020-05-19 14:26:14',
                'locked_by_admin' => 0,
                'position' => 30,
                'created_at' => '2019-07-19 10:47:25',
                'updated_at' => '2020-05-19 14:26:14',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 121,
                'title' => 'Company Telephone Clean',
                'cgroup' => 'company',
                'key' => 'company_telephone_clean',
                'value' => NULL,
                'locked_by_admin' => 0,
                'position' => 31,
                'created_at' => '2019-07-21 18:50:40',
                'updated_at' => '2019-07-21 18:54:45',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 122,
                'title' => 'Google Tag manager ID',
                'cgroup' => 'company',
                'key' => 'google_tagmanager_id',
                'value' => NULL,
                'locked_by_admin' => 0,
                'position' => 32,
                'created_at' => '2019-08-12 18:53:46',
                'updated_at' => '2023-02-10 20:27:53',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 127,
                'title' => 'OpenGraph Type',
                'cgroup' => 'opengraph',
                'key' => 'og_type',
                'value' => 'website',
                'locked_by_admin' => 0,
                'position' => 114,
                'created_at' => '2019-10-03 20:52:19',
                'updated_at' => '2019-10-18 12:36:50',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 128,
                'title' => 'OpenGraph Image Width',
                'cgroup' => 'opengraph',
                'key' => 'og_image_width',
                'value' => '1200',
                'locked_by_admin' => 0,
                'position' => 115,
                'created_at' => '2019-10-03 21:01:45',
                'updated_at' => '2019-10-03 21:01:51',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 129,
                'title' => 'OpenGraph Image Height',
                'cgroup' => 'opengraph',
                'key' => 'og_image_height',
                'value' => '630',
                'locked_by_admin' => 0,
                'position' => 116,
                'created_at' => '2019-10-03 21:02:21',
                'updated_at' => '2019-10-18 12:36:57',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 130,
                'title' => 'OpenGraph Description Max Length',
                'cgroup' => 'opengraph',
                'key' => 'og_descr_max',
                'value' => '300',
                'locked_by_admin' => 0,
                'position' => 117,
                'created_at' => '2019-10-03 21:03:12',
                'updated_at' => '2019-10-03 21:04:54',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 131,
                'title' => 'OpenGraph Site Name',
                'cgroup' => 'opengraph',
                'key' => 'og_site_name',
                'value' => 'Firmaq Media',
                'locked_by_admin' => 0,
                'position' => 118,
                'created_at' => '2019-10-18 12:37:44',
                'updated_at' => '2019-10-18 13:31:43',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 132,
                'title' => 'Eve Version',
                'cgroup' => 'system',
                'key' => 'lara_eve_version',
                'value' => '8.5.0',
                'locked_by_admin' => 0,
                'position' => 119,
                'created_at' => '2020-08-11 17:09:21',
                'updated_at' => '2024-11-06 11:25:54',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 134,
                'title' => 'Top post range days',
                'cgroup' => 'general',
                'key' => 'top_post_range_days',
                'value' => '60',
                'locked_by_admin' => 0,
                'position' => 121,
                'created_at' => '2021-08-05 18:29:35',
                'updated_at' => '2021-08-05 18:31:10',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 135,
                'title' => 'Company Facebook Account',
                'cgroup' => 'company',
                'key' => 'company_facebook_account',
                'value' => '#',
                'locked_by_admin' => 0,
                'position' => 122,
                'created_at' => '2023-03-12 13:11:38',
                'updated_at' => '2023-03-12 13:11:40',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 136,
                'title' => 'Company Instagram Account',
                'cgroup' => 'company',
                'key' => 'company_instagram_account',
                'value' => '#',
                'locked_by_admin' => 0,
                'position' => 123,
                'created_at' => '2023-03-12 13:12:04',
                'updated_at' => '2023-03-12 13:12:10',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 137,
                'title' => 'Company Twitter Account',
                'cgroup' => 'company',
                'key' => 'company_twitter_account',
                'value' => '#',
                'locked_by_admin' => 0,
                'position' => 124,
                'created_at' => '2023-03-12 13:12:46',
                'updated_at' => '2023-03-12 13:12:53',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 138,
                'title' => 'Company Linkedin Account',
                'cgroup' => 'company',
                'key' => 'company_linkedin_account',
                'value' => '#',
                'locked_by_admin' => 0,
                'position' => 125,
                'created_at' => '2023-03-12 13:13:23',
                'updated_at' => '2023-03-12 13:13:26',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 139,
                'title' => 'Team Photo Ratio',
                'cgroup' => 'company',
                'key' => 'company_team_photo_ratio',
                'value' => '1x1',
                'locked_by_admin' => 0,
                'position' => 126,
                'created_at' => '2023-03-12 13:13:23',
                'updated_at' => '2023-06-29 14:21:34',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 143,
                'title' => 'Lara Translation Version',
                'cgroup' => 'system',
                'key' => 'lara_translation_version',
                'value' => '8.7.0',
                'locked_by_admin' => 0,
                'position' => 127,
                'created_at' => '2023-10-24 15:48:06',
                'updated_at' => '2025-09-03 16:53:58',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 144,
                'title' => 'Seo Description Max Length',
                'cgroup' => 'system',
                'key' => 'seo_desc_max_len',
                'value' => '300',
                'locked_by_admin' => 0,
                'position' => 128,
                'created_at' => '2024-04-19 11:08:59',
                'updated_at' => '2024-04-19 11:08:59',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 145,
                'title' => 'Seo Keywords Max Length',
                'cgroup' => 'system',
                'key' => 'seo_keyw_max_len',
                'value' => '300',
                'locked_by_admin' => 0,
                'position' => 129,
                'created_at' => '2024-04-19 11:10:40',
                'updated_at' => '2024-04-19 11:10:40',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 146,
                'title' => 'last_media_file_sync_page',
                'cgroup' => 'system',
                'key' => 'last_media_file_sync_page',
                'value' => '2025-07-06 14:42:58',
                'locked_by_admin' => 0,
                'position' => 130,
                'created_at' => '2024-08-10 16:37:02',
                'updated_at' => '2025-07-06 14:42:58',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 147,
                'title' => 'last_media_videofile_sync_page',
                'cgroup' => 'system',
                'key' => 'last_media_videofile_sync_page',
                'value' => '2025-07-06 14:42:58',
                'locked_by_admin' => 0,
                'position' => 131,
                'created_at' => '2024-08-10 16:37:02',
                'updated_at' => '2025-07-06 14:42:58',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 148,
                'title' => 'last_media_file_sync_blog',
                'cgroup' => 'system',
                'key' => 'last_media_file_sync_blog',
                'value' => '2025-04-12 17:37:06',
                'locked_by_admin' => 0,
                'position' => 132,
                'created_at' => '2024-10-14 14:06:42',
                'updated_at' => '2025-04-12 17:37:06',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 149,
                'title' => 'last_media_videofile_sync_blog',
                'cgroup' => 'system',
                'key' => 'last_media_videofile_sync_blog',
                'value' => '2025-04-12 17:37:06',
                'locked_by_admin' => 0,
                'position' => 133,
                'created_at' => '2024-10-14 14:06:42',
                'updated_at' => '2025-04-12 17:37:06',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 150,
                'title' => 'last_media_file_sync_team',
                'cgroup' => 'system',
                'key' => 'last_media_file_sync_team',
                'value' => '2025-04-10 20:05:32',
                'locked_by_admin' => 0,
                'position' => 134,
                'created_at' => '2024-10-24 16:17:41',
                'updated_at' => '2025-04-10 20:05:32',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 152,
                'title' => 'Company 2FA App Name',
                'cgroup' => 'company',
                'key' => 'company_2fa_app_name',
                'value' => 'Lara CMS 8',
                'locked_by_admin' => 0,
                'position' => 135,
                'created_at' => '2025-01-17 13:36:28',
                'updated_at' => '2025-01-17 13:36:28',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 153,
                'title' => 'last_media_file_sync_product',
                'cgroup' => 'system',
                'key' => 'last_media_file_sync_product',
                'value' => '2025-05-09 15:00:48',
                'locked_by_admin' => 0,
                'position' => 136,
                'created_at' => '2025-05-08 14:43:05',
                'updated_at' => '2025-05-09 15:00:48',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 154,
                'title' => 'last_media_videofile_sync_product',
                'cgroup' => 'system',
                'key' => 'last_media_videofile_sync_product',
                'value' => '2025-05-09 15:00:48',
                'locked_by_admin' => 0,
                'position' => 137,
                'created_at' => '2025-05-08 14:43:05',
                'updated_at' => '2025-05-09 15:00:48',
                'deleted_at' => NULL,
            ),
        ));


    }
}