<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraObjectTagsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_object_tags')->delete();
        
        \DB::table('lara_object_tags')->insert(array (
            0 => 
            array (
                'id' => 2059,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Tech',
                'slug' => 'tech',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'tech',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-22 10:18:23',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 0,
                'position' => 202001,
            ),
            1 => 
            array (
                'id' => 2060,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'blogs',
                'title' => 'Home Blog Widget',
                'slug' => 'home-blog-widget',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => NULL,
                'locked_by_admin' => 1,
                'created_at' => '2025-06-22 10:19:10',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 15,
                'rgt' => 16,
                'depth' => 0,
                'position' => 102001,
            ),
            2 => 
            array (
                'id' => 2061,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Strategy',
                'slug' => 'strategy',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'strategy',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-22 10:22:05',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 17,
                'rgt' => 18,
                'depth' => 0,
                'position' => 202002,
            ),
            3 => 
            array (
                'id' => 2062,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'blogs',
                'title' => 'Team News',
                'slug' => 'team-news',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => NULL,
                'locked_by_admin' => 1,
                'created_at' => '2025-06-22 10:45:26',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 19,
                'rgt' => 24,
                'depth' => 0,
                'position' => 102002,
            ),
            4 => 
            array (
                'id' => 2063,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Software',
                'slug' => 'software',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'software',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:05:03',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 25,
                'rgt' => 26,
                'depth' => 0,
                'position' => 202003,
            ),
            5 => 
            array (
                'id' => 2064,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Processes & Tools',
                'slug' => 'processes-tools',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'processes-tools',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:05:17',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 27,
                'rgt' => 28,
                'depth' => 0,
                'position' => 202004,
            ),
            6 => 
            array (
                'id' => 2065,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Startups',
                'slug' => 'startups',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'startups',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:05:40',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 29,
                'rgt' => 30,
                'depth' => 0,
                'position' => 202005,
            ),
            7 => 
            array (
                'id' => 2066,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Digital',
                'slug' => 'digital',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'digital',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:05:54',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 31,
                'rgt' => 32,
                'depth' => 0,
                'position' => 202006,
            ),
            8 => 
            array (
                'id' => 2067,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'blogs',
                'title' => 'Business',
                'slug' => 'business',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'business',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:06:09',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 33,
                'rgt' => 34,
                'depth' => 0,
                'position' => 202007,
            ),
            9 => 
            array (
                'id' => 2068,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'blogs',
                'title' => 'Tech Team News',
                'slug' => 'tech-team-news',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'tech-team-news',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:36:54',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => 2062,
                'lft' => 20,
                'rgt' => 21,
                'depth' => 1,
                'position' => 102003,
            ),
            10 => 
            array (
                'id' => 2069,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'blogs',
                'title' => 'Marketing Team News',
                'slug' => 'marketing-team-news',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => NULL,
                'route' => 'marketing-team-news',
                'locked_by_admin' => 0,
                'created_at' => '2025-06-24 08:37:08',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => 2062,
                'lft' => 22,
                'rgt' => 23,
                'depth' => 1,
                'position' => 102004,
            ),
            11 => 
            array (
                'id' => 2073,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'sliders',
                'title' => 'home',
                'slug' => 'home',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'home',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-06 17:43:17',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 35,
                'rgt' => 36,
                'depth' => 0,
                'position' => 142001,
            ),
            12 => 
            array (
                'id' => 2074,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'sliders',
                'title' => 'pagetitle',
                'slug' => 'pagetitle',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'pagetitle',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-06 17:46:14',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 37,
                'rgt' => 38,
                'depth' => 0,
                'position' => 142002,
            ),
            13 => 
            array (
                'id' => 2075,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'sliders',
                'title' => ' sidebar',
                'slug' => 'sidebar',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'sidebar',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-06 17:46:23',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 39,
                'rgt' => 40,
                'depth' => 0,
                'position' => 142003,
            ),
            14 => 
            array (
                'id' => 2076,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'sliders',
                'title' => 'cases',
                'slug' => 'cases',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'cases',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-06 17:46:33',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 41,
                'rgt' => 42,
                'depth' => 0,
                'position' => 142004,
            ),
            15 => 
            array (
                'id' => 2077,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'teams',
                'title' => 'Management',
                'slug' => 'management',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'management',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:22:02',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 43,
                'rgt' => 44,
                'depth' => 0,
                'position' => 103001,
            ),
            16 => 
            array (
                'id' => 2078,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'teams',
                'title' => 'Design',
                'slug' => 'design',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'design',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:22:13',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 45,
                'rgt' => 46,
                'depth' => 0,
                'position' => 103002,
            ),
            17 => 
            array (
                'id' => 2079,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'teams',
                'title' => 'Development',
                'slug' => 'development',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'development',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:22:31',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 47,
                'rgt' => 48,
                'depth' => 0,
                'position' => 103003,
            ),
            18 => 
            array (
                'id' => 2080,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'teams',
                'title' => 'Communication',
                'slug' => 'communication',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'communication',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:22:39',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 49,
                'rgt' => 50,
                'depth' => 0,
                'position' => 103004,
            ),
            19 => 
            array (
                'id' => 2081,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'teams',
                'title' => 'Projects',
                'slug' => 'projects',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'projects',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:22:51',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 51,
                'rgt' => 52,
                'depth' => 0,
                'position' => 103005,
            ),
            20 => 
            array (
                'id' => 2082,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'teams',
                'title' => 'Freelance',
                'slug' => 'freelance',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'freelance',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 13:23:10',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 53,
                'rgt' => 54,
                'depth' => 0,
                'position' => 0,
            ),
            21 => 
            array (
                'id' => 2083,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'events',
                'title' => 'Laravel',
                'slug' => 'laravel',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'laravel',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 18:19:10',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 55,
                'rgt' => 56,
                'depth' => 0,
                'position' => 0,
            ),
            22 => 
            array (
                'id' => 2084,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'events',
                'title' => 'Test',
                'slug' => 'test',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'test',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 18:19:22',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 57,
                'rgt' => 58,
                'depth' => 0,
                'position' => 0,
            ),
            23 => 
            array (
                'id' => 2085,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'events',
                'title' => 'Tag 1',
                'slug' => 'tag-1',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'tag-1',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 18:19:36',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 59,
                'rgt' => 60,
                'depth' => 0,
                'position' => 244001,
            ),
            24 => 
            array (
                'id' => 2086,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'events',
                'title' => 'Tag 2',
                'slug' => 'tag-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'tag-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 18:19:45',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 61,
                'rgt' => 62,
                'depth' => 0,
                'position' => 244002,
            ),
            25 => 
            array (
                'id' => 2087,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'events',
                'title' => 'Tag 3',
                'slug' => 'tag-3',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'tag-3',
                'locked_by_admin' => 0,
                'created_at' => '2025-07-09 18:19:54',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 63,
                'rgt' => 64,
                'depth' => 0,
                'position' => 244003,
            ),
            26 => 
            array (
                'id' => 2088,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'services',
                'title' => 'Design',
                'slug' => 'design-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'design-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:43:37',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 65,
                'rgt' => 66,
                'depth' => 0,
                'position' => 161001,
            ),
            27 => 
            array (
                'id' => 2089,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'services',
                'title' => 'Development',
                'slug' => 'development-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'development-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:44:21',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 67,
                'rgt' => 68,
                'depth' => 0,
                'position' => 161002,
            ),
            28 => 
            array (
                'id' => 2090,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'services',
                'title' => 'Testing',
                'slug' => 'testing',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'testing',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:44:33',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 69,
                'rgt' => 70,
                'depth' => 0,
                'position' => 161003,
            ),
            29 => 
            array (
                'id' => 2091,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'services',
                'title' => 'UX',
                'slug' => 'ux',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'ux',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:45:59',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 71,
                'rgt' => 72,
                'depth' => 0,
                'position' => 261001,
            ),
            30 => 
            array (
                'id' => 2092,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'services',
                'title' => 'Responsive',
                'slug' => 'responsive',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'responsive',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:46:09',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 73,
                'rgt' => 74,
                'depth' => 0,
                'position' => 261002,
            ),
            31 => 
            array (
                'id' => 2093,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'services',
                'title' => 'Backend',
                'slug' => 'backend',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'backend',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:46:18',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 75,
                'rgt' => 76,
                'depth' => 0,
                'position' => 261003,
            ),
            32 => 
            array (
                'id' => 2094,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'services',
                'title' => 'Full Stack',
                'slug' => 'full-stack',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'full-stack',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-22 17:46:27',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 77,
                'rgt' => 78,
                'depth' => 0,
                'position' => 261004,
            ),
            33 => 
            array (
                'id' => 2095,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'testimonials',
                'title' => 'home',
                'slug' => 'home-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'home-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 12:38:55',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 79,
                'rgt' => 80,
                'depth' => 0,
                'position' => 0,
            ),
            34 => 
            array (
                'id' => 2096,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'testimonials',
                'title' => 'About',
                'slug' => 'about',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'about',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 12:39:08',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 81,
                'rgt' => 82,
                'depth' => 0,
                'position' => 0,
            ),
            35 => 
            array (
                'id' => 2097,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'portfolios',
                'title' => 'Brand',
                'slug' => 'brand',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'brand',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 13:10:30',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 83,
                'rgt' => 84,
                'depth' => 0,
                'position' => 163001,
            ),
            36 => 
            array (
                'id' => 2098,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'portfolios',
                'title' => 'Motion',
                'slug' => 'motion',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'motion',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 13:10:42',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 85,
                'rgt' => 86,
                'depth' => 0,
                'position' => 163002,
            ),
            37 => 
            array (
                'id' => 2099,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'portfolios',
                'title' => 'Printing',
                'slug' => 'printing',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'printing',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 13:10:51',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 87,
                'rgt' => 88,
                'depth' => 0,
                'position' => 163003,
            ),
            38 => 
            array (
                'id' => 2100,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'portfolios',
                'title' => 'Test',
                'slug' => 'test-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'test-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 13:11:13',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 89,
                'rgt' => 90,
                'depth' => 0,
                'position' => 163004,
            ),
            39 => 
            array (
                'id' => 2101,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'portfolios',
                'title' => 'Design',
                'slug' => 'design-3',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'design-3',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-24 13:11:27',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 91,
                'rgt' => 92,
                'depth' => 0,
                'position' => 163005,
            ),
            40 => 
            array (
                'id' => 2102,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'galleries',
                'title' => 'Team',
                'slug' => 'team',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'team',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-28 14:43:59',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 93,
                'rgt' => 94,
                'depth' => 0,
                'position' => 164001,
            ),
            41 => 
            array (
                'id' => 2103,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'galleries',
                'title' => 'Tech',
                'slug' => 'tech-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'tech-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-28 14:44:12',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 95,
                'rgt' => 96,
                'depth' => 0,
                'position' => 164002,
            ),
            42 => 
            array (
                'id' => 2104,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'galleries',
                'title' => 'Webdesign',
                'slug' => 'webdesign',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'webdesign',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-28 14:44:28',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 97,
                'rgt' => 98,
                'depth' => 0,
                'position' => 164003,
            ),
            43 => 
            array (
                'id' => 2105,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'galleries',
                'title' => 'Portfolio',
                'slug' => 'portfolio',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'portfolio',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-28 14:56:34',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 99,
                'rgt' => 100,
                'depth' => 0,
                'position' => 164004,
            ),
            44 => 
            array (
                'id' => 2106,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'docs',
                'title' => 'General',
                'slug' => 'general',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'general',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-29 13:28:55',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 101,
                'rgt' => 102,
                'depth' => 0,
                'position' => 0,
            ),
            45 => 
            array (
                'id' => 2107,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'docs',
                'title' => 'Legal',
                'slug' => 'legal',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'legal',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-29 13:29:59',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 103,
                'rgt' => 104,
                'depth' => 0,
                'position' => 0,
            ),
            46 => 
            array (
                'id' => 2108,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'docs',
                'title' => 'Design',
                'slug' => 'design-4',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'design-4',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-29 13:30:14',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 105,
                'rgt' => 106,
                'depth' => 0,
                'position' => 0,
            ),
            47 => 
            array (
                'id' => 2109,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 2,
                'resource_slug' => 'docs',
                'title' => 'Web Development',
                'slug' => 'web-development',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'web-development',
                'locked_by_admin' => 0,
                'created_at' => '2025-08-29 13:30:25',
                'updated_at' => '2025-10-09 18:34:57',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 107,
                'rgt' => 108,
                'depth' => 0,
                'position' => 0,
            ),
            48 => 
            array (
                'id' => 2110,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Cat 1',
                'slug' => 'cat-1',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => NULL,
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:23:27',
                'updated_at' => '2025-10-09 18:24:42',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 1,
                'rgt' => 6,
                'depth' => 0,
                'position' => 170001,
            ),
            49 => 
            array (
                'id' => 2111,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Cat 2',
                'slug' => 'cat-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => NULL,
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:25:06',
                'updated_at' => '2025-10-09 18:35:30',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 7,
                'rgt' => 14,
                'depth' => 0,
                'position' => 170004,
            ),
            50 => 
            array (
                'id' => 2112,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Sub 1.1',
                'slug' => 'sub-1-1',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => 'sub-1-1',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:25:42',
                'updated_at' => '2025-10-09 18:30:59',
                'publish' => 1,
                'parent_id' => 2110,
                'lft' => 2,
                'rgt' => 3,
                'depth' => 1,
                'position' => 170002,
            ),
            51 => 
            array (
                'id' => 2113,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Sub 2.1',
                'slug' => 'sub-2-1',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => 'sub-2-1',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:26:27',
                'updated_at' => '2025-10-09 18:35:30',
                'publish' => 1,
                'parent_id' => 2111,
                'lft' => 8,
                'rgt' => 9,
                'depth' => 1,
                'position' => 170005,
            ),
            52 => 
            array (
                'id' => 2114,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Sub 2.2',
                'slug' => 'sub-2-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => 'sub-2-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:26:45',
                'updated_at' => '2025-10-09 18:35:30',
                'publish' => 1,
                'parent_id' => 2111,
                'lft' => 10,
                'rgt' => 11,
                'depth' => 1,
                'position' => 170006,
            ),
            53 => 
            array (
                'id' => 2115,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Sub 2.3',
                'slug' => 'sub-2-3',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => 'sub-2-3',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:33:13',
                'updated_at' => '2025-10-09 18:35:30',
                'publish' => 1,
                'parent_id' => 2111,
                'lft' => 12,
                'rgt' => 13,
                'depth' => 1,
                'position' => 170007,
            ),
            54 => 
            array (
                'id' => 2117,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'products',
                'title' => 'Sub 1.2',
                'slug' => 'sub-1-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Lorem ipsum dolor sit amet</p>',
                'route' => 'sub-1-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-09 18:35:30',
                'updated_at' => '2025-10-09 18:35:30',
                'publish' => 1,
                'parent_id' => 2110,
                'lft' => 4,
                'rgt' => 5,
                'depth' => 1,
                'position' => 170003,
            ),
            55 => 
            array (
                'id' => 2118,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'cities',
                'title' => 'Cat 1',
                'slug' => 'cat-1-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => NULL,
                'locked_by_admin' => 0,
                'created_at' => '2025-10-21 13:12:42',
                'updated_at' => '2025-10-21 13:12:42',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 1,
                'rgt' => 6,
                'depth' => 0,
                'position' => 173001,
            ),
            56 => 
            array (
                'id' => 2119,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'cities',
                'title' => 'Cat 2',
                'slug' => 'cat-2-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => NULL,
                'locked_by_admin' => 0,
                'created_at' => '2025-10-21 13:12:55',
                'updated_at' => '2025-10-21 13:13:28',
                'publish' => 1,
                'parent_id' => NULL,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'position' => 173004,
            ),
            57 => 
            array (
                'id' => 2120,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'cities',
                'title' => 'Sub 1',
                'slug' => 'sub-1',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'sub-1',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-21 13:13:15',
                'updated_at' => '2025-10-21 13:13:15',
                'publish' => 1,
                'parent_id' => 2118,
                'lft' => 2,
                'rgt' => 3,
                'depth' => 1,
                'position' => 173002,
            ),
            58 => 
            array (
                'id' => 2121,
                'language' => 'nl',
                'language_parent' => NULL,
                'taxonomy_id' => 1,
                'resource_slug' => 'cities',
                'title' => 'Sub 2',
                'slug' => 'sub-2',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p></p>',
                'route' => 'sub-2',
                'locked_by_admin' => 0,
                'created_at' => '2025-10-21 13:13:28',
                'updated_at' => '2025-10-21 13:13:28',
                'publish' => 1,
                'parent_id' => 2118,
                'lft' => 4,
                'rgt' => 5,
                'depth' => 1,
                'position' => 173003,
            ),
        ));
        
        
    }
}