<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class DemoLaraContentTeamsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('lara_content_teams')->delete();

        \DB::table('lara_content_teams')->insert(array (
            0 =>
            array (
                'id' => 1,
                'location_id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Wilson',
                'slug' => 'jenny-wilson',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => 'JennyWilson15387',
                'twitter' => 'JennyWilson15387',
                'facebook' => 'JennyWilson15387',
                'email' => 'jenny.wilson@laracorp.com',
                'role' => 'Co-Founder & CEO',
                'middle_name' => NULL,
                'first_name' => 'Jenny',
                'created_at' => '2025-07-04 08:06:35',
                'updated_at' => '2025-10-20 09:38:15',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-04 17:39:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'location_id' => 1,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Edwards',
                'slug' => 'ralph-edwards',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Co-Founder',
                'middle_name' => NULL,
                'first_name' => 'Ralph',
                'created_at' => '2025-07-04 15:38:39',
                'updated_at' => '2025-09-03 13:50:42',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-04 15:38:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Williamson',
                'slug' => 'williamson',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Creative Director',
                'middle_name' => NULL,
                'first_name' => 'Cameron',
                'created_at' => '2025-07-09 13:33:20',
                'updated_at' => '2025-09-03 13:51:37',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:32:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Bell',
                'slug' => 'bell',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Marketing Director',
                'middle_name' => NULL,
                'first_name' => 'Jerome',
                'created_at' => '2025-07-09 13:35:21',
                'updated_at' => '2025-09-03 13:51:52',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:34:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'McKinney',
                'slug' => 'mckinney',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Lead Designer',
                'middle_name' => NULL,
                'first_name' => 'Marvin',
                'created_at' => '2025-07-09 13:36:13',
                'updated_at' => '2025-09-03 13:52:12',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:35:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Howard',
                'slug' => 'howard',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Motion Designer',
                'middle_name' => NULL,
                'first_name' => 'Esther',
                'created_at' => '2025-07-09 13:38:45',
                'updated_at' => '2025-09-03 13:52:41',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:38:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Steward',
                'slug' => 'steward',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Lead Developer',
                'middle_name' => NULL,
                'first_name' => 'Darrell',
                'created_at' => '2025-07-09 13:39:36',
                'updated_at' => '2025-09-03 13:53:10',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:39:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'location_id' => 3,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Cooper',
                'slug' => 'cooper',
                'slug_lock' => 0,
                'lead' => NULL,
                'body' => '<p>Suspendisse felis nulla, sollicitudin ut maximus ac, convallis nec ipsum. Fusce ac purus porttitor, dignissim nisi quis, volutpat risus. Etiam aliquam urna sem. Sed dignissim nisi ac dolor dapibus euismod.</p>',
                'linkedin' => '#',
                'twitter' => '#',
                'facebook' => '#',
                'email' => NULL,
                'role' => 'Senior Project Manager',
                'middle_name' => NULL,
                'first_name' => 'Jane',
                'created_at' => '2025-07-09 13:40:37',
                'updated_at' => '2025-09-03 13:53:29',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-09 13:40:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => NULL,
            ),
        ));


    }
}