<?php

namespace Lara\App\Database\Seeders;

use Illuminate\Database\Seeder;

class LaraContentPagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_content_pages')->delete();
        
        \DB::table('lara_content_pages')->insert(array (
            0 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'About our Company',
                'slug' => 'about',
                'slug_lock' => 0,
            'body' => '<div class="grid-layout" data-cols="2" style="--cols: repeat(2, minmax(0, 1fr));" data-from-breakpoint="md"><div class="grid-layout-col" data-col-span="1" style="--col-span: span 1 / span 1;"><p style="text-align: justify;">SH4 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam cursus ipsum quis velit suscipit, vitae porta mauris maximus. Proin interdum, dui sed egestas ullamcorper, metus felis facilisis eros, eu viverra metus est ut purus. Curabitur id ligula tempor, efficitur nibh eu, malesuada nulla. Sed mollis. Maecenas sit amet aliquam libero, quis tincidunt dolor. Nunc sem leo, imperdiet in molestie at, pharetra quis augue.</p></div><div class="grid-layout-col" data-col-span="1" style="--col-span: span 1 / span 1;"><p style="text-align: justify;">Duis cursus turpis nulla, ac accumsan quam sollicitudin vel. Etiam condimentum feugiat neque id interdum. Mauris in eros placerat, ultrices est vel, pretium lacus. Mauris porttitor ligula et mattis venenatis. Vivamus viverra ipsum at quam fermentum, eget interdum tortor venenatis. Maecenas pulvinar. Nunc condimentum libero ex, sit amet tincidunt lorem fringilla eget. Pellentesque id lobortis ex. Suspendisse.</p></div></div><div class="grid-layout" data-cols="3" style="--cols: repeat(3, minmax(0, 1fr));" data-from-breakpoint="lg"><div class="grid-layout-col" data-col-span="2" style="--col-span: span 2 / span 2;"><p style="text-align: justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam cursus ipsum quis velit suscipit, vitae porta mauris maximus. Proin interdum, dui sed egestas ullamcorper, metus felis facilisis eros, eu viverra metus est ut purus. Curabitur id ligula tempor, efficitur nibh eu, malesuada nulla. Sed mollis. Maecenas sit amet aliquam libero, quis tincidunt dolor. Nunc sem leo, imperdiet in molestie at, pharetra quis augue. Maecenas et ligula tempor nisi convallis ornare.</p></div><div class="grid-layout-col" data-col-span="1" style="--col-span: span 1 / span 1;"><p style="text-align: justify;"><img src="https://lara402.test/assets/media/AH0WeK3cg7BXvLBnvNR1fYrHiQ8mzZLHcAjLI05i.jpg" data-id="AH0WeK3cg7BXvLBnvNR1fYrHiQ8mzZLHcAjLI05i.jpg"></p></div></div><details><summary>Read more</summary><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ipsum mauris, porta eget lacus eu, fermentum dictum lectus. Suspendisse potenti. Duis vehicula iaculis porttitor. Fusce feugiat, arcu consectetur auctor placerat, purus enim dignissim nunc, eu sagittis ante nisl sed sapien.</p></details><a target="_blank" rel="noopener noreferrer nofollow" href="http://www.firmaq.nl/" class="btn btn-lg btn-primary">Testing 1234</a>',
                'body3' => '<p></p>',
                'body2' => '<p></p>',
                'menuroute' => '/about',
                'ishome' => '0',
                'template' => 'landing',
                'created_at' => '2025-04-21 18:47:38',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-04-21 18:47:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 1002,
                'cgroup' => 'page',
            ),
            1 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Design',
                'slug' => 'design',
                'slug_lock' => 0,
                'body' => NULL,
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-04-24 15:36:18',
                'updated_at' => '2025-08-29 14:26:12',
                'deleted_at' => '2025-08-29 14:26:12',
                'publish' => 1,
                'publish_from' => '2025-04-24 15:36:01',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => 'page',
            ),
            2 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Development',
                'slug' => 'development',
                'slug_lock' => 0,
                'body' => NULL,
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-04-24 15:36:58',
                'updated_at' => '2025-08-29 14:26:09',
                'deleted_at' => '2025-08-29 14:26:09',
                'publish' => 1,
                'publish_from' => '2025-04-24 15:36:52',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 0,
                'cgroup' => 'page',
            ),
            3 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Meet Lara',
                'slug' => 'home',
                'slug_lock' => 0,
                'body' => '<p>Erat pharetra sed at fringilla etiam nullam platea fringilla. Gravida sodales sit mauris amet massa justo. Egestas ipsum amet tortor hendrerit amet phasellus adipiscing. Eget porta posuere pellentesque sed commodo gravida dignissim dignissim iaculis. Elementum nibh duis at in.</p>',
                'body3' => NULL,
                'body2' => '<p></p>',
                'menuroute' => '/',
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-04-24 16:04:06',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-04-24 16:04:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 1001,
                'cgroup' => 'page',
            ),
            4 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Meet Our Team',
                'slug' => 'teams-index-module-nl',
                'slug_lock' => 0,
                'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur eleifend eleifend. Nam consectetur enim massa, non hendrerit nulla maximus quis. Nam dictum, nunc eu viverra semper, ante nibh gravida ante, sit amet lobortis diam lectus vel arcu. Nullam mollis justo quis euismod sollicitudin. Aliquam et ante ut nunc facilisis ultrices eleifend vel justo. Vestibulum aliquam, mi ac condimentum placerat, magna ex tristique mauris, ut porta dui enim ut massa. Nunc et tortor ac augue tincidunt scelerisque eget id ante. In in metus in neque porta elementum et ullamcorper enim.</p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-05-30 15:50:05',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-05-30 15:50:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8009,
                'cgroup' => 'module',
            ),
            5 => 
            array (
                'id' => 19,
                'user_id' => 3,
                'language' => 'en',
                'language_parent' => 2,
                'title' => '[en] About',
                'slug' => 'en-about',
                'slug_lock' => 0,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-07-13 12:51:47',
                'updated_at' => '2025-07-13 13:21:19',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-07-13 12:51:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 9001,
                'cgroup' => 'page',
            ),
            6 => 
            array (
                'id' => 25,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Privacy',
                'slug' => 'privacy',
                'slug_lock' => 0,
                'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in nunc varius, scelerisque ipsum sit amet, hendrerit velit. Vestibulum id odio varius, congue justo ac, tristique nulla. In euismod tortor eu eros laoreet, at molestie nunc rutrum. Nulla rutrum urna quis ligula pulvinar, ut sagittis massa gravida. Nullam pulvinar lacus turpis, vitae vulputate magna congue at. Quisque aliquet ante nisi, id condimentum libero feugiat non. Pellentesque efficitur eu est sit amet consequat.</p><p style="text-align: justify;">Vivamus et porttitor velit. In semper, quam eu gravida malesuada, sem leo posuere est, quis maximus urna justo non turpis. Nullam ac ultricies sem. Aliquam sit amet libero varius, congue odio sit amet, gravida erat. Cras nec dignissim ipsum. Vestibulum sagittis sapien nec mi pulvinar, a rutrum augue pulvinar. Aenean et velit leo. Maecenas vulputate id odio vehicula dignissim.</p><p style="text-align: justify;">Vivamus sed ligula magna. Integer sagittis ante ut placerat molestie. Fusce id eros tellus. Suspendisse varius ipsum ac lacus sollicitudin feugiat. Suspendisse et lacus lorem. Curabitur semper diam sapien, vel hendrerit risus consequat id. Suspendisse eu nulla vitae purus ultricies ornare eget eu lectus. Aenean orci est, gravida at vestibulum quis, sagittis ac ligula. Nunc vitae ipsum nec lectus sagittis pretium. Suspendisse ultrices risus eget ligula ultrices posuere et eget lectus.</p><p style="text-align: justify;">Ut tellus est, convallis vitae mollis ut, tempus ac diam. Curabitur mattis, felis quis imperdiet semper, diam dui consequat nisi, ac dapibus sapien tellus non felis. Aenean mollis turpis diam, nec congue leo aliquet non. Aenean cursus felis quis sem lobortis, eu vehicula nisi commodo. Fusce non condimentum nunc. Vivamus sed volutpat est. Nulla lacinia lorem eu mollis fermentum.</p><p style="text-align: justify;">Vivamus non tincidunt libero. Maecenas pellentesque libero ut enim viverra rutrum. Vivamus sed tincidunt magna, sed pellentesque nunc. Nunc sit amet blandit quam. Nullam fermentum velit non justo finibus, scelerisque dictum mauris iaculis. Nam et odio condimentum, scelerisque magna sit amet, elementum dui. Mauris tristique nibh non urna eleifend pharetra. Cras ante dui, porta a tristique sit amet, faucibus vitae velit. Nunc aliquet interdum lacus, ut posuere nisl euismod a. Nulla facilisi. Vestibulum eros justo, laoreet at felis ac, venenatis viverra neque.</p>',
                'body3' => NULL,
                'body2' => '<p></p>',
                'menuroute' => '/privacy-2',
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-08-29 14:26:47',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-29 14:26:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 2002,
                'cgroup' => 'page',
            ),
            7 => 
            array (
                'id' => 26,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Thank you',
                'slug' => 'thank-you',
                'slug_lock' => 0,
                'body' => NULL,
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => '/classicform/thank-you',
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-08-29 18:11:25',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-29 18:11:25',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 1015,
                'cgroup' => 'page',
            ),
            8 => 
            array (
                'id' => 34,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Blog',
                'slug' => 'blogs-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-08-31 14:53:47',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-08-31 14:53:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8001,
                'cgroup' => 'module',
            ),
            9 => 
            array (
                'id' => 35,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Our Services',
                'slug' => 'services-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-03 14:45:46',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-03 14:45:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8008,
                'cgroup' => 'module',
            ),
            10 => 
            array (
                'id' => 36,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Upcoming Events',
                'slug' => 'events-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-03 15:28:34',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-03 15:28:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8004,
                'cgroup' => 'module',
            ),
            11 => 
            array (
                'id' => 37,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Our Photo Album',
                'slug' => 'galleries-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-03 15:28:39',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-03 15:28:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8005,
                'cgroup' => 'module',
            ),
            12 => 
            array (
                'id' => 38,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Contact',
                'slug' => 'contactforms-form-module-nl',
                'slug_lock' => 1,
                'body' => '<h2>Development</h2><ul><li><p>Schipholweg 66, 2035 LB, Haarlem</p></li><li><p>085 2006261</p></li><li><p><strong>Mon - Fri</strong>: 9:00 - 17:00</p></li></ul><h2>Sales &amp; Support</h2><ul><li><p>Yme Kuiperweg 24, 8448 RT, Heerenveen</p></li><li><p>085 2006261</p></li><li><p><strong>Mon - Fri</strong>: 9:00 - 17:00</p></li></ul>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-05 08:32:55',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-05 08:32:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8002,
                'cgroup' => 'module',
            ),
            13 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Contactforms Email Title',
                'slug' => 'contactforms-email-nl',
                'slug_lock' => 1,
                'body' => '',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => NULL,
                'created_at' => '2025-09-05 09:14:15',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-05 09:14:15',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 9001,
                'cgroup' => 'email',
            ),
            14 => 
            array (
                'id' => 40,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Our Videos',
                'slug' => 'videos-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-06 15:22:02',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-06 15:22:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8011,
                'cgroup' => 'module',
            ),
            15 => 
            array (
                'id' => 41,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Downloads',
                'slug' => 'docs-index-module-nl',
                'slug_lock' => 1,
                'body' => '<p></p>',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-06 17:44:38',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-06 17:44:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8003,
                'cgroup' => 'module',
            ),
            16 => 
            array (
                'id' => 42,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Oops',
                'slug' => '404',
                'slug_lock' => 1,
                'body' => '<p>The page you requested can not be found. Please use the menu to find the information you&#039;re looking for.</p>',
                'body3' => NULL,
                'body2' => '<p></p>',
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => 'standard',
                'created_at' => '2025-09-08 15:44:52',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-09-08 15:44:00',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 9002,
                'cgroup' => 'page',
            ),
            17 => 
            array (
                'id' => 43,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Locations Index Module Page',
                'slug' => 'locations-index-module-nl',
                'slug_lock' => 1,
                'body' => '',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => NULL,
                'created_at' => '2025-10-06 15:56:36',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-10-06 15:56:36',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8006,
                'cgroup' => 'module',
            ),
            18 => 
            array (
                'id' => 44,
                'user_id' => 3,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Products Index Module Page',
                'slug' => 'products-index-module-nl',
                'slug_lock' => 1,
                'body' => '',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => NULL,
                'created_at' => '2025-10-21 08:06:20',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-10-21 08:06:20',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8007,
                'cgroup' => 'module',
            ),
            19 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'language' => 'nl',
                'language_parent' => NULL,
                'title' => 'Users Form Module Page',
                'slug' => 'users-form-module-nl',
                'slug_lock' => 1,
                'body' => '',
                'body3' => NULL,
                'body2' => NULL,
                'menuroute' => NULL,
                'ishome' => '0',
                'template' => NULL,
                'created_at' => '2025-10-24 08:54:28',
                'updated_at' => '2025-10-24 12:46:45',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2025-10-24 08:54:28',
                'publish_expire' => 0,
                'publish_to' => NULL,
                'publish_hide' => 0,
                'position' => 8010,
                'cgroup' => 'module',
            ),
        ));
        
        
    }
}